-- NEXUS OS — shipped vocabulary
--
-- GENERATED from Supabase project dsvuoovivysszdoiorch on 2026-09-04.
-- Do not hand-edit; regenerate.
--
-- WHY THIS FILE EXISTS, AND WHY A SCHEMA-ONLY BASELINE IS NOT A RESTORE HERE.
-- Measured, not assumed. Replaying the migration chain onto a catalogue-derived
-- baseline that carried the schema and no rows, migration
--   20260904024105_wapolicy_02_intent_catalogue_and_platform_rules
-- failed with
--   insert or update on table "policy_rule" violates foreign key constraint
--   "policy_rule_rule_type_fkey"
-- and 20260904025050_wapolicy_04_close_default_grants then failed after it,
-- because the object the first one would have created did not exist. Two of the
-- 55 forward migrations, one root cause: this system keeps its vocabulary in
-- TABLES, migrations INSERT against that vocabulary, and a schema-only restore
-- has none of it. A restore without this file looks complete and fails on the
-- next migration that names a rule type.
--
-- WHAT IS IN HERE, AND WHAT IS DELIBERATELY NOT.
-- In: shipped product vocabulary — reason codes, state models, units,
-- jurisdictions, capability catalogue, provider capability. It is the same for
-- every dealership and is seeded by migrations today.
-- NOT in: `tenants` (the dealership's own identity), `workflow_registry` (real
-- n8n workflow ids, trigger detail and is_active flags — CLAUDE.md calls that
-- operational configuration, not shipped vocabulary, and it is the subject of a
-- known tenancy finding), and every tenant-scoped table. A restore gets no
-- dealership data from this repository, by design.
--
-- ON CONFLICT DO NOTHING throughout: this is safe to re-run and will not
-- overwrite a value an operator has since changed.

-- policy_jurisdiction
INSERT INTO public.policy_jurisdiction (code, owner_kind, owner_name, what_it_covers, added_at) VALUES
  ('AE'::text, 'REGULATOR'::text, 'The applicable United Arab Emirates federal authority'::text, 'Rules a UAE regulator imposes. A dealership is subject to these; it does not write them.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone),
  ('GLOBAL'::text, 'NEXUS'::text, 'NEXUS OS'::text, 'Claims NEXUS itself makes that are not tied to a platform or a territory. Mostly research claims recorded as questions.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone),
  ('NEXUS_HOUSE'::text, 'NEXUS'::text, 'NEXUS OS'::text, 'Rules NEXUS chooses to impose on every dealership, stricter than any platform or regulator requires. Recorded as our choice, never as somebody else''s requirement.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone),
  ('PLATFORM_WHATSAPP'::text, 'PLATFORM'::text, 'Meta Platforms, Inc. (WhatsApp Business Platform)'::text, 'Rules Meta imposes on every business using the WhatsApp Business Platform. Only the platform operator, holding the Meta account, may verify one.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone),
  ('TENANT_HOUSE'::text, 'TENANT'::text, 'The dealership itself'::text, 'The only namespace a dealership legislates in. A house rule here may tighten what a platform or regulator allows; it can never loosen it, and it binds nobody but the dealership that wrote it.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone),
  ('UNSPECIFIED'::text, 'NEXUS'::text, 'Nobody - the jurisdiction has never been established'::text, 'A holding namespace for constants lifted out of the codebase whose legislator was never identified. Nothing here should ever be authoritative.'::text, '2026-09-04 07:07:54.469583+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- policy_rule_type
INSERT INTO public.policy_rule_type (code, label, description, created_at) VALUES
  ('CAMPAIGN'::text, 'Campaign'::text, 'Rules governing advertising and promotion: price-claim substantiation, mandatory disclosures, prize and finance-advert requirements.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('COMPLIANCE'::text, 'Compliance'::text, 'Rules imposing an obligation on the dealership itself: KYC/AML thresholds, record retention, reporting duties, licence conditions.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('EXPORT'::text, 'Export'::text, 'Rules restricting or conditioning the sale of a vehicle OUT of a jurisdiction: export certificates, de-registration, age or emissions limits at the border.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('FINANCE'::text, 'Finance'::text, 'Rules governing lending against a vehicle: LTV ceilings, down-payment floors, maximum tenure, rate-disclosure obligations, permitted lenders.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('IMPORT'::text, 'Import'::text, 'Rules restricting or conditioning bringing a vehicle INTO a jurisdiction: age limits, left/right hand drive, homologation, duty rates.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('MESSAGING'::text, 'Messaging'::text, 'Rules governing contacting a person: consent, opt-out, permitted hours, channel-specific windows, template pre-approval.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('TAX'::text, 'Tax'::text, 'Rules imposing or exempting a tax on a vehicle transaction: VAT rate, registration duty, margin-scheme treatment.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('VEHICLE_ELIGIBILITY'::text, 'Vehicle eligibility'::text, 'Rules about which vehicles may lawfully be sold, financed, registered or advertised in a jurisdiction, independent of who the buyer is.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- policy_unit
INSERT INTO public.policy_unit (code, label, value_kind, description, created_at) VALUES
  ('AED'::text, 'UAE dirham'::text, 'NUMERIC'::text, 'An absolute amount in AED.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('AED_PER_DAY'::text, 'UAE dirham per day'::text, 'NUMERIC'::text, 'An AED amount accruing once per calendar day.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('BOOLEAN'::text, 'Permitted / not'::text, 'BOOLEAN'::text, 'The rule permits or forbids. Stored as the text true/false.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('COUNT'::text, 'Count'::text, 'NUMERIC'::text, 'A dimensionless count of things.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('DAYS'::text, 'Days'::text, 'NUMERIC'::text, 'A whole number of days.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('ENUM'::text, 'Enumerated value'::text, 'TEXT'::text, 'The rule names one of a fixed set of options; the set belongs in notes.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('HOURS'::text, 'Hours'::text, 'NUMERIC'::text, 'A whole number of hours.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('ISO_DATE'::text, 'Date'::text, 'TEXT'::text, 'The rule IS a date (a deadline, a cut-off). Stored ISO-8601.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('MINUTES'::text, 'Minutes'::text, 'NUMERIC'::text, 'A whole number of minutes.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('MONTHS'::text, 'Months'::text, 'NUMERIC'::text, 'A whole number of months.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('MULTIPLIER'::text, 'Multiplier'::text, 'NUMERIC'::text, 'A dimensionless factor applied to another figure. 1.87 means "times 1.87".'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('PCT'::text, 'Percent'::text, 'NUMERIC'::text, 'A percentage expressed out of 100. 5 means five percent, NOT 0.05.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('RATIO'::text, 'Ratio'::text, 'NUMERIC'::text, 'A dimensionless fraction. 0.05 means five percent. Use PCT unless the source itself publishes a ratio.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('SCORE'::text, 'Score'::text, 'NUMERIC'::text, 'A point on a named scale; the scale itself belongs in notes.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('TEXT'::text, 'Free text'::text, 'TEXT'::text, 'The rule is prose and has no numeric form. Quote the source, do not paraphrase it.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone),
  ('YEARS'::text, 'Years'::text, 'NUMERIC'::text, 'A whole number of years.'::text, '2026-09-03 03:56:16.397243+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- attribution_link_basis
INSERT INTO public.attribution_link_basis (basis, rank, is_evidence, default_confidence, label, description) VALUES
  ('FOREIGN_KEY'::text, '1'::integer, 'true'::boolean, 'HIGH'::text, 'Declared foreign key'::text, 'A FOREIGN KEY constraint enforced by Postgres. The strongest link this database can hold: the value cannot point at a row that is not there. Example: purchase_history.lead_id -&gt; leads(id).'::text),
  ('HUMAN_CONFIRMED_LINK'::text, '2'::integer, 'true'::boolean, 'HIGH'::text, 'Confirmed by a named person'::text, 'A named member of staff at this dealership was shown two records and confirmed they are the same piece of business, and the confirmation is stored against their identity. Strong, but it is a statement of belief by a person and not a fact about the schema. Already in use by inventory_actions.attribution_basis.'::text),
  ('LINK_FIELD_EMPTY'::text, '7'::integer, 'false'::boolean, 'NONE'::text, 'The column exists and is empty here'::text, 'A column that could carry this edge exists on the row and is NULL. UNKNOWN, not none: a NULL lead_id on a sale means nobody recorded which lead it came from, NOT that the sale came from no lead. Nothing downstream may read it as zero.'::text),
  ('MODEL_TEXT_ONLY'::text, '5'::integer, 'false'::boolean, 'NONE'::text, 'Text coincidence - REFUSED'::text, 'Free-text vehicle words on one record overlap free-text vehicle words on another. This is a prompt for a person, never evidence. The live proof is in this database: the one real sale reads "Lexus LX 600 2024" at AED 585,000, which is character-for-character the model of unit NX-1011 and exactly its list price - and NX-1011 is still marked Available. The text matches perfectly and proves nothing. Same word as public.action_outcome_candidates() uses.'::text),
  ('NATURAL_KEY_MATCH'::text, '3'::integer, 'true'::boolean, 'HIGH'::text, 'Exact match on a tenant-scoped natural key'::text, 'Two rows carry byte-identical values in a column pair that this database treats as a business key and scopes per dealership, with no FOREIGN KEY behind it. Example: purchase_history.deal_id = deals_embeddings.deal_id. Strong but unenforced: nothing stops a writer breaking it.'::text),
  ('NO_LINK_FIELD'::text, '8'::integer, 'false'::boolean, 'NONE'::text, 'No column anywhere could carry this edge'::text, 'The schema has no column on either side that could hold this relationship, so no row-level evidence can exist for it at all. This is a finding about the integration backlog, not about the row.'::text),
  ('NO_SOURCE_TABLE'::text, '9'::integer, 'false'::boolean, 'NONE'::text, 'Neither end of this edge exists as data'::text, 'One or both of the things being linked has no table in this database. Nothing can be linked, counted, or displayed. Sell as roadmap, never as capability.'::text),
  ('RESOLVED_IDENTITY'::text, '4'::integer, 'true'::boolean, 'MEDIUM'::text, 'Resolved by the identity rule, ambiguity refused'::text, 'Established by the one identity rule this system owns - v_lead_messages and nexus_lead_for_comm_key in Postgres, lib/identity.js in the browser (INV-002). Exact email, else the last nine digits of a phone but ONLY when that tail belongs to exactly one person, else a bridge through whatsapp_contacts for an @lid handle. A shared tail matches nobody. MEDIUM rather than HIGH because it is a rule applied to text, not a key: it is designed to refuse rather than to be certain.'::text),
  ('SAME_ROW'::text, '0'::integer, 'true'::boolean, 'HIGH'::text, 'Both facts are columns of one row'::text, 'No edge has to be established because there is nothing to join: the two facts sit on the same record. Example: a sale and its amount_aed. The strongest possible basis, and the only one that cannot break.'::text),
  ('UNRESOLVED_KEY'::text, '6'::integer, 'false'::boolean, 'NONE'::text, 'Key present, resolves to nobody - REFUSED'::text, 'The record carries a key for the other end of the edge, but the identity rule (INV-002) resolves it to nobody: either no lead matches it, or more than one does and the rule refuses to choose. UNKNOWN, not none. A WhatsApp @lid handle with no whatsapp_contacts bridge is the common case here - 55 of 108 communication_logs rows on 3 Sep 2026.'::text)
ON CONFLICT DO NOTHING;

-- channel_send_form
INSERT INTO public.channel_send_form (code, label, description, requires_template_ref, is_media, is_business_safe_outside_window, sort, created_at) VALUES
  ('FREEFORM_AUDIO'::text, 'Free-form audio'::text, 'An audio file or voice note composed at send time.'::text, 'false'::boolean, 'true'::boolean, 'false'::boolean, '40'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('FREEFORM_DOCUMENT'::text, 'Free-form document'::text, 'A document (PDF, spreadsheet) composed at send time.'::text, 'false'::boolean, 'true'::boolean, 'false'::boolean, '30'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('FREEFORM_IMAGE'::text, 'Free-form image'::text, 'An image, optionally with a caption, composed at send time.'::text, 'false'::boolean, 'true'::boolean, 'false'::boolean, '20'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('FREEFORM_TEXT'::text, 'Free-form text'::text, 'A plain text body composed at send time.'::text, 'false'::boolean, 'false'::boolean, 'false'::boolean, '10'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('FREEFORM_VIDEO'::text, 'Free-form video'::text, 'A video composed at send time.'::text, 'false'::boolean, 'true'::boolean, 'false'::boolean, '50'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('INTERACTIVE_BUTTONS'::text, 'Interactive reply buttons'::text, 'A message offering the customer tappable reply buttons.'::text, 'false'::boolean, 'false'::boolean, 'false'::boolean, '80'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('INTERACTIVE_LIST'::text, 'Interactive list'::text, 'A message offering the customer a list to pick from.'::text, 'false'::boolean, 'false'::boolean, 'false'::boolean, '90'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('TEMPLATE_MEDIA_HEADER'::text, 'Approved template with media header'::text, 'A pre-approved template whose header carries an image, video or document.'::text, 'true'::boolean, 'true'::boolean, 'true'::boolean, '70'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('TEMPLATE_TEXT'::text, 'Approved template'::text, 'A message template pre-approved by the platform, with variable substitution.'::text, 'true'::boolean, 'false'::boolean, 'true'::boolean, '60'::integer, '2026-09-04 03:06:46.580233+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- tenant_capability_catalogue
INSERT INTO public.tenant_capability_catalogue (capability_key, label, what_it_unlocks, requires, absent_means, sort, created_at) VALUES
  ('APPOINTMENTS'::text, 'Appointments and showroom diary'::text, 'The strongest in-flight signal a dealership has, no-show recovery, and Lead Recovery APPOINTMENT_PENDING.'::text, 'An appointments table or calendar feed with a lead or deal reference, a scheduled time, and an outcome (kept / no-show / cancelled).'::text, 'Any state or action that depends on an appointment is reported UNREACHABLE with the reason, not merely empty. Nothing may say a customer did not book.'::text, '20'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('CRM_SYNC'::text, 'Two-way sync with the dealership CRM or DMS'::text, 'Ownership, stage and outcome that stay true when the sales floor works outside NEXUS.'::text, 'A CRM or DMS integration with a stable customer key.'::text, 'NEXUS reports only what it observed itself and does not claim to reflect the CRM. A lead absent here may exist there.'::text, '100'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('DEAL_RECORD'::text, 'In-flight deal record'::text, 'Deal Rescue as a population rather than a screen: a deal that exists while it is still in flight, with customer, vehicle, agreed value and owner.'::text, 'A deal row created at first commitment rather than at sale, written by whatever the sales floor actually uses.'::text, 'Deal Rescue reports that there is no deal record to rescue and names the integration. It must not present closed sales as a rescue pipeline.'::text, '30'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('EMAIL_OUTBOUND'::text, 'Outbound email from the dealership domain'::text, 'Email follow-up steps and email recovery actions.'::text, 'A registered, active email channel with a verified sending domain.'::text, 'No email is sent and no email action is offered.'::text, '90'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('FINANCE_DECISION'::text, 'Lender decision on a finance application'::text, 'FINANCE_BLOCKED as a real state, and finance-led recovery actions.'::text, 'Lender, decision, decided_at and conditions recorded against a quote.'::text, 'No finance state is asserted. A quote without a decision is an unanswered quote, not a declined one.'::text, '40'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('HOLDING_RATE'::text, 'A stated cost of holding a unit for a day'::text, 'Holding cost accrued, and any recommendation that trades days in stock against money.'::text, 'A rate this dealership stated, with source, owner, date and basis - the four parts inventory_profit_settings already demands.'::text, 'Holding cost is NOT_COMPUTABLE. This is the exact fabrication that put AED 50 a day on twelve units nobody had been asked about; the absent state must stay visible.'::text, '70'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('MARKET_COMPARABLES'::text, 'Priced market comparables'::text, 'A market position on a unit: over, under or at market, and the reprice recommendation that follows.'::text, 'Competitor listings matched to our unit at exact or strong quality, scraped inside the freshness window.'::text, 'Market position is UNKNOWN and the underlying listings are shown as evidence. Never an average, never inferred, never a position derived from weak matches.'::text, '50'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('SERVICE_HISTORY'::text, 'Service and repair-order history'::text, 'Service Retention: due-for-service outreach, declined-work recovery, and lifetime value that includes the workshop.'::text, 'A feed of repair orders or service visits keyed to a customer or a vehicle, with dates and line items.'::text, 'The Service Retention module reports NOT AVAILABLE - no service feed is connected - and shows nothing else. It must never display a zero, an empty trend, or a "no services due" message, because absence of data is not absence of services.'::text, '10'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('UNIT_COST'::text, 'Acquisition cost on every unit'::text, 'Gross margin, net margin and every profit figure the Inventory Profit Sentinel produces.'::text, 'cost_aed populated on the units in scope.'::text, 'Margin is NOT_COMPUTABLE and the inputs are shown instead. Never a margin computed against a list price alone.'::text, '60'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('WHATSAPP_OUTBOUND'::text, 'Outbound WhatsApp on the dealership number'::text, 'Automated replies, follow-up steps and recovery actions delivered on WhatsApp.'::text, 'A registered, active WhatsApp channel in public.channel_registry and approved message templates.'::text, 'No WhatsApp is sent and no WhatsApp action is offered. An action that cannot be delivered must not be proposed.'::text, '80'::integer, '2026-09-03 20:48:15.961058+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- attribution_edge_type
INSERT INTO public.attribution_edge_type (edge, seq, from_node, to_node, state, basis, source_ref, finding, unlocked_by, unlock_rank) VALUES
  ('CAMPAIGN_ENROLMENT'::text, '11'::integer, 'campaign'::text, 'lead'::text, 'ABSENT_NO_TABLE'::text, 'NO_SOURCE_TABLE'::text, 'n8n 7-Day Warm Lead Drip Campaign; audit_log'::text, 'Enrolment into the 7-day drip is queued inside n8n and lands in no table here. audit_log holds 5 rows for "7-Day Warm Lead Drip Campaign" and 0 of them carry a lead_email, so not one of them can be attached to a person. A lead can be enrolled while this database has no record that it happened.'::text, 'An enrolment table written by the drip workflow at enrol time, carrying tenant, lead and campaign.'::text, '4'::integer),
  ('CAMPAIGN_SEND_TO_ENGAGEMENT'::text, '12'::integer, 'send'::text, 'open/click/reply'::text, 'ABSENT_NO_TABLE'::text, 'NO_SOURCE_TABLE'::text, 'nothing'::text, 'No table records a delivery, an open, a click or an unsubscribe. A Gmail send leaves no event behind here. This is not a figure that is missing - it is a figure that has never existed in this database.'::text, 'A sending provider that posts delivery and engagement webhooks into a table this database can read.'::text, '7'::integer),
  ('CAMPAIGN_TO_LEAD'::text, '10'::integer, 'campaign'::text, 'lead'::text, 'ABSENT_NO_TABLE'::text, 'NO_SOURCE_TABLE'::text, 'no campaigns table in any schema; leads.source'::text, 'THE WEAKEST LINK, AND THE ONE THE OWNER CARES MOST ABOUT. There is no campaigns table anywhere in this database - not in public, not in any other schema. leads.source exists but holds the name of the internal workflow that created the row: "nexus-master-router" on 3 of 3 leads, one distinct value. It is a pipeline label, not a marketing channel. There is no utm field, no ad id, no click id, no referrer and no landing-page record. "Which channel made me money" CANNOT BE ANSWERED TODAY, at any confidence, and no view in this migration set will pretend otherwise.'::text, 'A lead-capture path that writes the channel, campaign and click id onto the lead at creation (Meta/Google lead ads, the website form, Dubizzle/YallaMotor feeds), plus a campaigns table to name them.'::text, '1'::integer),
  ('CONVERSATION_TO_VEHICLE'::text, '40'::integer, 'message'::text, 'inventory unit'::text, 'TEXT_ONLY_REFUSED'::text, 'MODEL_TEXT_ONLY'::text, 'communication_logs.message vs inventory.model, via nexus_model_tokens()'::text, 'Same refusal as LEAD_TO_VEHICLE. The Profit Sentinel already counts these token overlaps as an enquiry signal and already caps its own confidence because of them - its enquiry_coverage reads INSUFFICIENT today. Attribution holds the harder line: a token overlap is not an edge.'::text, 'The BDC agent recording the unit it quoted, at the moment it quotes it.'::text, '5'::integer),
  ('DEAL_TO_DEAL_RECORD'::text, '55'::integer, 'sale record'::text, 'deal embedding'::text, 'PRESENT_KEYED'::text, 'NATURAL_KEY_MATCH'::text, 'purchase_history.deal_id = deals_embeddings.deal_id'::text, 'Both rows carry the identical synthetic key "auto:&lt;email&gt;|&lt;date&gt;". Scoped per dealership since 2 Sep. Exact, but unenforced - there is no FOREIGN KEY behind it, so a writer could break it without the database objecting.'::text, NULL, NULL),
  ('DEAL_TO_FINANCE'::text, '75'::integer, 'sale record'::text, 'finance quote'::text, 'ABSENT_NO_FIELD'::text, 'NO_LINK_FIELD'::text, 'neither table references the other'::text, 'purchase_history carries no quote id and no calculation_id; finance_quotes carries no sale id. NEXUS cannot say whether a sale was financed, at what rate, or by whom - only that a quote and a sale exist for the same person. Two quotes for one person and one sale would be unattributable.'::text, 'A calculation_id column on the sale, populated from the quote the deal actually closed on.'::text, '8'::integer),
  ('DEAL_TO_MARGIN'::text, '65'::integer, 'sale record'::text, 'gross profit'::text, 'BLOCKED_BY_UPSTREAM'::text, 'NO_LINK_FIELD'::text, 'inventory.cost_aed, reachable only through DEAL_TO_VEHICLE'::text, 'Revenue on a sale is CONFIRMED - it is a column of the sale. Gross profit on a sale is NOT COMPUTABLE, because the cost sits on the inventory unit and nothing ties the sale to a unit. So NEXUS can tell this dealership what it sold for and cannot tell it what it made. Unknown, not zero.'::text, 'Whatever unlocks DEAL_TO_VEHICLE. Nothing else is needed - cost_aed is already present on all 12 units.'::text, '2'::integer),
  ('DEAL_TO_REPEAT_PURCHASE'::text, '95'::integer, 'sale record'::text, 'later sale'::text, 'PRESENT_KEYED'::text, 'FOREIGN_KEY'::text, 'purchase_history.lead_id, two sales sharing one lead'::text, 'Structurally sound the moment a second sale exists: two purchase_history rows carrying the same lead_id are the same customer by key, not by guess. Unexercised - there is one sale in the whole database.'::text, NULL, NULL),
  ('DEAL_TO_REVENUE'::text, '80'::integer, 'sale record'::text, 'revenue'::text, 'PRESENT_SAME_ROW'::text, 'SAME_ROW'::text, 'purchase_history.amount_aed'::text, 'CONFIRMED revenue - not attributed, not estimated. AED 585,000 on the one sale. It is a column of the sale record, so there is no edge to break.'::text, NULL, NULL),
  ('DEAL_TO_SERVICE'::text, '90'::integer, 'sale record'::text, 'service visit'::text, 'ABSENT_NO_TABLE'::text, 'NO_SOURCE_TABLE'::text, 'nothing'::text, 'No service table, no appointment table, no recon-cost column. Ownership-lifecycle attribution after the sale cannot start. Roadmap, never capability.'::text, 'A DMS or service-system connection.'::text, '9'::integer),
  ('DEAL_TO_VEHICLE'::text, '60'::integer, 'sale record'::text, 'inventory unit'::text, 'ABSENT_NO_FIELD'::text, 'NO_LINK_FIELD'::text, 'purchase_history has no vin, no stock number, no inventory id; inventory_actions.outcome_purchase_id is the only route'::text, 'THE BREAK THAT COSTS THE MOST MONEY. purchase_history holds no reference to an inventory unit of any kind. The one real sale reads "Lexus LX 600 2024" at AED 585,000 - character-for-character the model of unit NX-1011 and exactly its list price - and NX-1011 is STILL MARKED AVAILABLE. The text matches perfectly and proves nothing. The only route that exists today is a person confirming it through action_record_outcome(), which stores HUMAN_CONFIRMED_LINK; 0 of the 3 inventory actions have done so.'::text, 'A stock number or VIN column on the sale, written by whatever records the sale. The dashboard deal form is the cheapest place to add it.'::text, '2'::integer),
  ('LEAD_TO_CONVERSATION'::text, '20'::integer, 'lead'::text, 'message'::text, 'PRESENT_RESOLVED'::text, 'RESOLVED_IDENTITY'::text, 'v_lead_messages; nexus_lead_for_comm_key(text,uuid); lib/identity.js'::text, 'REAL, but by rule rather than by key. communication_logs.lead_email is one text column holding four incompatible key shapes for the same person. The identity rule resolves 53 of 108 rows across 15 distinct keys; the rest belong to WhatsApp handles that match no lead. Unresolved is UNKNOWN, not "no conversation".'::text, NULL, NULL),
  ('LEAD_TO_DEAL'::text, '50'::integer, 'lead'::text, 'sale record'::text, 'PRESENT_KEYED'::text, 'FOREIGN_KEY'::text, 'purchase_history.lead_id -&gt; leads(id)'::text, 'THE ONE STRONG LINK IN THE CHAIN. Added 2 Sep 2026 and populated on the one real sale (lead 38). It is written only when the deal was picked from a lead in the dashboard; a hand-typed deal posts no lead_id at all, so NULL here is a normal state meaning "nobody recorded it", never "no lead exists".'::text, NULL, NULL),
  ('LEAD_TO_FINANCE'::text, '70'::integer, 'lead'::text, 'finance quote'::text, 'PRESENT_RESOLVED'::text, 'RESOLVED_IDENTITY'::text, 'finance_quotes.lead_email'::text, 'Resolvable by the same identity rule, but finance_quotes holds 0 rows today, so this hop has never carried a real edge. Note that screens/finance.js joins the raw lead_email string rather than importing lib/identity.js - narrower than the rule, so it will MISS a customer rather than misattribute one.'::text, NULL, NULL),
  ('LEAD_TO_VEHICLE'::text, '30'::integer, 'lead'::text, 'inventory unit'::text, 'TEXT_ONLY_REFUSED'::text, 'MODEL_TEXT_ONLY'::text, 'leads.vehicle_interest vs inventory.model, via nexus_model_tokens()'::text, 'leads carries NO vehicle reference - no VIN, no stock number, no inventory id. vehicle_interest is free text a customer typed. Lead 38 reads "Hi, I saw the lexus LX 600 2024 on your website. Is it still available?" which shares model words with NX-1011, and that is a prompt for a person, not a link. Two of the three leads have vehicle_interest holding an operator note about a wrong number, not a vehicle at all.'::text, 'A vehicle picker on the lead form, or a website enquiry that posts the stock number the customer was looking at.'::text, '3'::integer),
  ('UNIT_ACTION_TO_DEAL'::text, '66'::integer, 'inventory action'::text, 'sale record'::text, 'PRESENT_HUMAN_ONLY'::text, 'HUMAN_CONFIRMED_LINK'::text, 'inventory_actions.outcome_purchase_id -&gt; purchase_history(id)'::text, 'A real foreign key, but one only a named person can populate, via action_record_outcome(). It exists precisely because DEAL_TO_VEHICLE does not. 3 actions exist, 0 are ATTRIBUTED, so this key has never been exercised on live data. It works; it does not scale past a few sales a month.'::text, NULL, NULL)
ON CONFLICT DO NOTHING;

-- attribution_event_type
INSERT INTO public.attribution_event_type (event, seq, state, source_ref, finding) VALUES
  ('DEAL_CREATED'::text, '50'::integer, 'PRESENT_CONFLATED'::text, 'purchase_history.created_at'::text, 'purchase_history only ever records a CLOSED-WON deal. There is no open-deal record, so DEAL_CREATED and SALE_CONFIRMED are the same row and cannot be separated in time. The gap between them - the part of the funnel where deals are lost - is invisible.'::text),
  ('DEAL_UPDATED'::text, '60'::integer, 'ABSENT_NO_SOURCE'::text, 'nothing'::text, 'No deal-stage table, no status column on the sale, no history table. Nothing in this database records a deal changing. Deal Rescue is blocked on this, not on code.'::text),
  ('FINANCE_QUOTE'::text, '70'::integer, 'PRESENT_NO_ROWS'::text, 'finance_quotes.created_at'::text, 'The table and the write path exist and have worked before; the table holds 0 rows today because a journey teardown clears them. Empty means cleared, not never.'::text),
  ('LEAD_CREATED'::text, '10'::integer, 'PRESENT'::text, 'leads.created_at'::text, 'Real. 3 rows, all created by the WhatsApp -&gt; Router wiring; 2 of the 3 were auto-created in error and are quarantined as DISQUALIFIED.'::text),
  ('MESSAGE_RECEIVED'::text, '20'::integer, 'PRESENT'::text, 'communication_logs, direction=inbound, filtered by nexus_is_message()'::text, 'Real. Filtered by the message predicate so a silence marker is not counted as a message (INV-004).'::text),
  ('MESSAGE_SENT'::text, '30'::integer, 'PRESENT'::text, 'communication_logs, direction=outbound, filtered by nexus_is_message()'::text, 'Real. Same predicate. Outbound rows on channel "system" are the dealership writing ABOUT a conversation rather than inside it, and are excluded.'::text),
  ('SALE_CONFIRMED'::text, '80'::integer, 'PRESENT'::text, 'purchase_history.purchase_date'::text, 'Real. One row. AED 585,000 on 2 Sep 2026, carrying lead_id 38.'::text),
  ('VEHICLE_INTEREST'::text, '40'::integer, 'PRESENT_UNRESOLVED'::text, 'leads.vehicle_interest; inbound communication_logs.message'::text, 'The event exists; the vehicle it points at does not resolve to a unit. Emitted with the unit UNKNOWN and the reason attached, never with a guessed unit.'::text)
ON CONFLICT DO NOTHING;

-- channel_provider_capability
INSERT INTO public.channel_provider_capability (provider, send_form, support_state, basis, evidence, verified_at, set_by, created_at) VALUES
  ('waha'::text, 'FREEFORM_AUDIO'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'WAHA sendVoice / sendFile against a session. Documented by WAHA; not exercised on this deployment.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'FREEFORM_DOCUMENT'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'WAHA sendFile against a session. Documented by WAHA; not exercised on this deployment.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'FREEFORM_IMAGE'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'WAHA sendImage / sendFile against a session. Documented by WAHA; not exercised on this deployment.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'FREEFORM_TEXT'::text, 'SUPPORTED'::text, 'MEASURED_HERE'::text, 'Proven live 2 Sep 2026: a real inbound WhatsApp message on the alba-cars WAHA session "default" was answered with an inventory-grounded free-form reply in 17.8 seconds, with a SUCCESS audit row. This is the one send this deployment has actually performed.'::text, '2026-09-02 00:00:00+00'::timestamp with time zone, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'FREEFORM_VIDEO'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'WAHA sendVideo against a session. Documented by WAHA; not exercised on this deployment.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'INTERACTIVE_BUTTONS'::text, 'NOT_SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Interactive reply buttons are a Business API construct. WAHA exposure of them against a personal client is unreliable and has been withdrawn and reinstated across releases; NEXUS will not route a customer-facing message onto a surface whose behaviour changes between provider builds. This deployment has already been shown to be running two different WAHA builds (2026.7.1 and 2026.7.2) against the same account.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'INTERACTIVE_LIST'::text, 'NOT_SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'As INTERACTIVE_BUTTONS.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'TEMPLATE_MEDIA_HEADER'::text, 'NOT_SUPPORTED'::text, 'STRUCTURAL'::text, 'Same reason as TEMPLATE_TEXT: there is no approved template object behind a WAHA session, so there is no header component to populate.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('waha'::text, 'TEMPLATE_TEXT'::text, 'NOT_SUPPORTED'::text, 'STRUCTURAL'::text, 'A WhatsApp message template is a WABA object: it is submitted to Meta, reviewed, approved, and then referenced by name and language on a Cloud API send. WAHA drives a WhatsApp client on the dealership own handset identity; there is no WABA behind it and therefore no approved template for it to reference. A "template" sent through WAHA would be an ordinary free-form message with the template text pasted into it - which is precisely a business-initiated message outside the service window, sent without the platform charge and without the platform review. That is a policy bypass, not a workaround, and it is the fastest way to get the dealership own number banned.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'FREEFORM_AUDIO'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=audio. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'FREEFORM_DOCUMENT'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=document. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'FREEFORM_IMAGE'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=image with a media id or link. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'FREEFORM_TEXT'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages accepts type=text inside the customer service window. Not yet exercised on this deployment - no whatsapp_cloud integration is registered.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'FREEFORM_VIDEO'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=video. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'INTERACTIVE_BUTTONS'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=interactive, interactive.type=button. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'INTERACTIVE_LIST'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=interactive, interactive.type=list. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'TEMPLATE_MEDIA_HEADER'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API template with a header component of type image/video/document. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, 'TEMPLATE_TEXT'::text, 'SUPPORTED'::text, 'VENDOR_DOCUMENTED'::text, 'Meta Cloud API /messages type=template against a template approved on the WABA. This is the only sanctioned way to open a conversation outside the service window. Not yet exercised here.'::text, NULL, 'chanroute_01'::text, '2026-09-04 03:06:46.580233+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- channel_provider_rank
INSERT INTO public.channel_provider_rank (provider, rank, is_official_platform, rationale, set_by, created_at) VALUES
  ('waha'::text, '90'::integer, 'false'::boolean, 'An unofficial transport driving a WhatsApp client on the dealership own number. Adequate for replying inside a conversation the customer started; never the right carrier for business-initiated traffic when an official integration exists, because that use is what gets a number banned.'::text, 'chanroute_02'::text, '2026-09-04 03:07:28.957342+00'::timestamp with time zone),
  ('whatsapp_cloud'::text, '10'::integer, 'true'::boolean, 'The official WhatsApp Business Platform. Template approval, signed webhooks, delivery receipts and platform-honoured opt-out all exist only here. It is also the provider that costs money, which is why it is ranked first and not last: this ordering is deliberately not an economic one.'::text, 'chanroute_02'::text, '2026-09-04 03:07:28.957342+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- deal_rescue_evidence_sources
INSERT INTO public.deal_rescue_evidence_sources (source, sort, admitted, evidence_tier, claim, verdict_basis) VALUES
  ('APPROVED_UNEXECUTED_INVENTORY_ACTION'::text, '80'::integer, 'false'::boolean, 'REFUSED'::text, 'An inventory_actions row with status APPROVED and executed_at null.'::text, 'A stalled action on a unit is not a stalled deal: there is no customer, no agreed price and no transaction - only a decision somebody has not carried out. The Inventory Action Center owns it and reports it. 1 such row exists today (NX-1010, REPRICE, approved 02 Sep 2026, never executed).'::text),
  ('APPROVED_UNEXECUTED_LEAD_RECOVERY_ACTION'::text, '90'::integer, 'false'::boolean, 'REFUSED'::text, 'A lead_recovery_actions row with status APPROVED and executed_at null.'::text, 'Same shape, and worse: Lead Recovery already surfaces it as action_state on the lead. Raising a deal from it would double-count one piece of work and put it on two screens with two owners.'::text),
  ('CONFIRMED_SALE'::text, '60'::integer, 'false'::boolean, 'REFUSED'::text, 'A purchase_history row.'::text, 'The deal is done - there is nothing to rescue. purchase_history is written AT the sale and its deal_id is synthesised in the same instant, so a sale row is not the tail of a deal record, it is the whole of it. What is known about a completed sale is answered by v_attribution_sale_chain.'::text),
  ('CONVERSATION_TRAFFIC'::text, '50'::integer, 'false'::boolean, 'REFUSED'::text, 'Recent inbound or outbound messages resolving to a lead under INV-002.'::text, 'Traffic evidences a conversation, which Lead Recovery already grades from these exact timestamps. It does not evidence a deal. This engine READS v_lead_recovery.silence_state rather than re-deriving silence, so that one fact keeps one derivation.'::text),
  ('DEAL_EMBEDDING'::text, '70'::integer, 'false'::boolean, 'REFUSED'::text, 'A deals_embeddings row.'::text, 'Written in the same second as the sale from the same payload and keyed on the identical synthesised deal_id. It is a RAG mirror of purchase_history, not an independent deal record.'::text),
  ('FINANCE_QUOTE'::text, '10'::integer, 'true'::boolean, 'STRONG'::text, 'A priced, dated finance offer against a specific vehicle value for a named person, with no sale on record.'::text, 'A quote is a commitment step: somebody priced a specific car for a specific person and wrote it down. That is a transaction under way rather than an enquiry, and it is the only deal-grade artefact this schema has a table for. It holds 0 live rows today (18 inserts, 15 deletes - journey teardowns), so this source is real but unpopulated.'::text),
  ('KYC_DOCUMENT_VALID'::text, '20'::integer, 'true'::boolean, 'WEAK'::text, 'A government identity document accepted (is_valid, not voided, not rejected) for a named person with no sale on record.'::text, 'Identity papers are normally collected to paper a transaction. Admitted only WEAKLY, because in this system the KYC workflow audits ANY image sent over WhatsApp - the document proves an image arrived, not that a deal exists. A weak candidate can only reach NEEDS_MANAGER; it never produces a risk state on its own. All 3 rows on file today are NOT_A_DOCUMENT, REJECTED and voided.'::text),
  ('LEAD_AGE'::text, '40'::integer, 'false'::boolean, 'REFUSED'::text, 'A leads row that is simply old.'::text, 'Old is not stalled. Age on its own is never a reason in this engine, for any state.'::text),
  ('OPEN_LEAD'::text, '30'::integer, 'false'::boolean, 'REFUSED'::text, 'A leads row whose status nexus_lead_is_open() treats as open.'::text, 'An open lead is an enquiry. Nothing about it says a price was agreed, a vehicle was chosen or a transaction started. Treating it as an in-flight deal would manufacture a deal lifecycle this dealership does not have. Lead Recovery (v_lead_recovery) already owns open leads and states their risk; a second engine over the same rows would put two states on one fact.'::text)
ON CONFLICT DO NOTHING;

-- deal_rescue_prerequisites
INSERT INTO public.deal_rescue_prerequisites (id, sort, requirement, kind, unlocks, unlocks_states, evidence_today, why_not_code) VALUES
  ('ACTION_LANE'::text, '80'::integer, 'deal_rescue_actions + deal_rescue_action_events, copied from lead_recovery_actions and reusing action_approver_context() for authority - propose, decide, execute, outcome.'::text, 'PRODUCT'::text, 'The ability to act on a rescue and be held to it, and to attribute a recovered deal to the action that saved it.'::text, '{}'::text[], 'DELIBERATELY NOT BUILT on 03 Sep 2026. The queue it would serve is structurally empty: 0 in-flight deals. An approval desk with nothing to approve is a third authority surface, a third audit vocabulary and eight more SECURITY DEFINER functions to keep out of anon''s reach, in exchange for no decision anybody can take.'::text, 'It is pure code and it is a near-copy of a lane that already works. Build it the day DEAL_RECORD lands, not before.'::text),
  ('APPOINTMENT'::text, '30'::integer, 'An appointments table with a lead or deal reference, a scheduled time and an outcome (kept / no-show / cancelled).'::text, 'INTEGRATION'::text, 'The strongest in-flight signal a dealership has, plus no-show recovery. One integration, two engines: it also unlocks Lead Recovery''s APPOINTMENT_PENDING, which is recorded there as UNREACHABLE_BY_DESIGN for exactly this reason.'::text, '{AT_RISK,STALLED}'::text[], 'No appointment table, no column, no event type. PRODUCT.md records the same gap.'::text, 'Appointments live in the dealership''s calendar or CRM. Creating a table NEXUS alone writes to would produce a diary nobody keeps.'::text),
  ('DEAL_OWNER'::text, '70'::integer, 'An owner on the deal record - the person who acts when it stalls.'::text, 'DATA'::text, 'MANAGER_REVIEW and FOLLOW_UP that name somebody. An action with no owner is an action nobody does.'::text, '{}'::text[], 'leads.assigned_to_id is null on 2 of 3 leads. There is no deal record to hang an owner on at all.'::text, 'The column exists on leads and is simply unpopulated; on a deal record it does not exist yet.'::text),
  ('DEAL_RECORD'::text, '10'::integer, 'A deal record created at first commitment rather than at sale: a row that exists while the deal is still in flight, carrying customer, vehicle, agreed value and an owner.'::text, 'SCHEMA'::text, 'The population itself. Without it Deal Rescue has nothing to rank, and every state below is unreachable for want of rows rather than for want of logic.'::text, '{ON_TRACK,AT_RISK,STALLED,CUSTOMER_GHOSTED,NEEDS_MANAGER}'::text[], 'No deals table exists. purchase_history holds 1 row, written at the moment of sale; its deal_id is synthesised then as ''auto:&lt;email&gt;|&lt;date&gt;''. deals_embeddings mirrors that row. So DEAL_CREATED and SALE_CONFIRMED are one event and DEAL_UPDATED is emitted by nothing.'::text, 'The table is cheap; deciding WHO writes it and WHEN is the work. It has to be written by whatever the sales floor actually uses - the CRM or the DMS - or it will be an empty table with a form nobody fills in.'::text),
  ('DEAL_STAGE_HISTORY'::text, '20'::integer, 'Stage and stage_changed_at on the deal record, appended rather than overwritten.'::text, 'SCHEMA'::text, 'A stalled deal that can say WHAT it is stuck on. Today the engine can only say a deal has not moved; it cannot say it has sat in Negotiation for nine days, which is the sentence a sales manager acts on.'::text, '{STALLED,AT_RISK}'::text[], 'No stage column and no history table anywhere in the schema. Nothing records that any deal ever occupied an earlier stage.'::text, 'An append-only stage log is code, but it is worthless until something upstream emits stage changes - which is the same integration as DEAL_RECORD.'::text),
  ('DEAL_TO_UNIT_LINK'::text, '50'::integer, 'A hard link from the deal (and from purchase_history) to inventory: unit id or VIN, not free text.'::text, 'SCHEMA'::text, 'Value at stake on an in-flight deal, and gross margin on a completed one. Turns "a deal is at risk" into "AED N of gross margin is at risk", which is the difference between a warning and a decision.'::text, '{}'::text[], 'v_attribution_sale_chain grades the VEHICLE hop UNKNOWN_TEXT_ONLY and MARGIN NOT_COMPUTABLE on the single sale on file: inventory.cost_aed is present on all 12 units, but nothing ties the sale to one.'::text, 'The column is code. Populating it means the person recording a sale has to pick the unit, which is a workflow change on the dashboard and in n8n.'::text),
  ('FINANCE_DECISION'::text, '40'::integer, 'A lender decision on finance_quotes: lender, decision, decided_at, conditions - plus quotes actually being written and kept.'::text, 'SCHEMA'::text, 'FINANCE_BLOCKED and the FINANCE_REVIEW action, which are unreachable together today and would become reachable together.'::text, '{FINANCE_BLOCKED}'::text[], 'finance_quotes has 35 columns and not one records a decision. It also holds 0 live rows (18 inserts, 15 deletes). Two independent blockers.'::text, 'The column is trivial. The decision comes from a bank, so the value in it is an integration.'::text),
  ('SILENCE_DETECTOR_RESUMED'::text, '60'::integer, 'The 12-Hour Silence Detector running and succeeding again.'::text, 'OPERATIONAL'::text, 'A CUSTOMER_GHOSTED that can be trusted. Today the state can be computed from message timestamps, but the corroborating marker is worthless.'::text, '{CUSTOMER_GHOSTED}'::text[], 'Last successful run 26 Aug 2026 19:03 UTC - 7 days stale as of 03 Sep 2026. v_lead_recovery.silence_detector_state = STALE for every lead.'::text, 'This one is not code and not an integration. It is a paused workflow on the n8n box.'::text),
  ('VOLUME'::text, '90'::integer, 'One real dealership using the system.'::text, 'DATA'::text, 'Everything. Thresholds picked against 3 leads and 1 sale are guesses.'::text, '{}'::text[], 'leads = 3 (2 of them quarantined wrong-number junk), purchase_history = 1, finance_quotes = 0.'::text, 'Not code at any price.'::text)
ON CONFLICT DO NOTHING;

-- deal_rescue_states
INSERT INTO public.deal_rescue_states (state, sort, meaning, engine_can_produce, blocked_by, requires) VALUES
  ('AT_RISK'::text, '20'::integer, 'An admitted in-flight deal that has not moved for longer than the dealership''s at-risk window, but not yet long enough to call stalled.'::text, 'true'::boolean, NULL, 'Latest movement older than at_risk_days and newer than stalled_days. Note this is inactivity, not a stage: nothing in this schema records that a deal is sitting in a stage.'::text),
  ('CUSTOMER_GHOSTED'::text, '40'::integer, 'An admitted in-flight deal that is stalled AND the customer specifically has gone quiet.'::text, 'true'::boolean, NULL, 'Stalled, plus v_lead_recovery.silence_state = SILENT_PAST_STALE_THRESHOLD on the lead. Silence is READ from Lead Recovery, never re-derived here - one figure, one derivation. Read with care: the 12-Hour Silence Detector last succeeded 26 Aug 2026 19:03 UTC and is stale, so the ABSENCE of a silence marker is not evidence that nobody went quiet.'::text),
  ('FINANCE_BLOCKED'::text, '60'::integer, 'A finance application carries a recorded adverse decision that is holding the deal up.'::text, 'false'::boolean, 'NO_FINANCE_DECISION_FIELD'::text, 'A lender decision on record. finance_quotes has 35 columns and not one records a decision - no status, no approved/declined flag, no decided_at, no conditions, no lender - and the table holds 0 live rows. Either of those alone would be fatal. NO BRANCH of deal_rescue_state() returns this state and none has been written; the value exists here only so the vocabulary is complete and so the prerequisite that would unlock it is named. Adding a branch before the column exists would be fabrication.'::text),
  ('NEEDS_MANAGER'::text, '50'::integer, 'Something transactional is on file and NEXUS cannot responsibly grade it. A person must look.'::text, 'true'::boolean, NULL, 'Admitted on WEAK evidence only, or the deal evidence is live while the lead it resolves to is closed. Never produced from age alone.'::text),
  ('ON_TRACK'::text, '10'::integer, 'An admitted in-flight deal that has moved inside the at-risk window.'::text, 'true'::boolean, NULL, 'An admitted deal-evidence row whose latest movement (the evidence row itself, or the last resolved message on the lead) is newer than at_risk_days.'::text),
  ('STALLED'::text, '30'::integer, 'An admitted in-flight deal that has not moved for longer than the stalled window, with no silence cause established.'::text, 'true'::boolean, NULL, 'Latest movement older than stalled_days. Inactivity only - the reason is UNKNOWN, because no stage history exists to say what it is stuck on.'::text),
  ('UNKNOWN'::text, '70'::integer, 'No admitted deal evidence, or the identity behind the evidence could not be resolved to one person.'::text, 'true'::boolean, NULL, 'The default. Unknown is not none and it is not zero: it means NEXUS cannot see, not that nothing is happening.'::text)
ON CONFLICT DO NOTHING;

-- inventory_action_reason_codes
INSERT INTO public.inventory_action_reason_codes (code, applies_to, label, meaning, engine_was_wrong, sort) VALUES
  ('ALREADY_ACTIONED'::text, '{REJECT}'::text[], 'Already done outside NEXUS'::text, 'The price was already moved, or the unit was already promoted, and NEXUS did not see it.'::text, 'true'::boolean, '40'::integer),
  ('COST_BASIS_WRONG'::text, '{REJECT}'::text[], 'Acquisition cost is wrong'::text, 'The cost_aed NEXUS holds for this unit is not what the dealership paid, so the margin it reasoned from is wrong.'::text, 'true'::boolean, '20'::integer),
  ('DAYS_IN_STOCK_WRONG'::text, '{REJECT}'::text[], 'Days in stock is wrong'::text, 'The unit has not been on the lot as long as NEXUS thinks - wrong acquisition date, or it came back from somewhere.'::text, 'true'::boolean, '30'::integer),
  ('DEAL_IN_PROGRESS'::text, '{REJECT,DEFER}'::text[], 'A deal is in progress'::text, 'Somebody is negotiating on this car right now. Moving the price mid-deal is not on.'::text, 'false'::boolean, '70'::integer),
  ('OTHER'::text, '{REJECT,DEFER}'::text[], 'Something else'::text, 'None of the above. The note is the whole record, so it has to say enough to be counted later.'::text, 'false'::boolean, '999'::integer),
  ('PRICE_IS_CORRECT'::text, '{REJECT}'::text[], 'The price is right'::text, 'The unit is priced correctly for this market and this car. The ageing is real; the conclusion is not.'::text, 'true'::boolean, '10'::integer),
  ('STRATEGIC_HOLD'::text, '{REJECT,DEFER}'::text[], 'Deliberate hold'::text, 'The dealership is holding this unit on purpose. The engine read the numbers correctly and the answer is still no.'::text, 'false'::boolean, '60'::integer),
  ('UNIT_NOT_AVAILABLE'::text, '{REJECT}'::text[], 'Unit is not actually available'::text, 'Sold, reserved, in workshop or otherwise not on the lot. NEXUS thinks it is available.'::text, 'true'::boolean, '50'::integer),
  ('WAITING_ON_APPROVAL'::text, '{DEFER}'::text[], 'Waiting on someone else'::text, 'The decision needs a person who has not been asked yet.'::text, 'false'::boolean, '80'::integer),
  ('WAITING_ON_MARKET'::text, '{DEFER}'::text[], 'Waiting for market evidence'::text, 'Not enough is known about what this car is worth to move on it yet.'::text, 'false'::boolean, '90'::integer)
ON CONFLICT DO NOTHING;

-- lead_recovery_reason_codes
INSERT INTO public.lead_recovery_reason_codes (code, applies_to, label, meaning, engine_was_wrong, sort) VALUES
  ('ALREADY_CONTACTED'::text, '{REJECT}'::text[], 'Already contacted outside NEXUS'::text, 'Somebody called, messaged or met this person through a channel NEXUS cannot see, so the silence NEXUS measured is not real silence. NEXUS was wrong because it was blind, not because the rule is wrong.'::text, 'true'::boolean, '20'::integer),
  ('CUSTOMER_ASKED_FOR_SPACE'::text, '{REJECT,DEFER}'::text[], 'Customer asked not to be chased'::text, 'The customer said they would come back to us. Chasing them is the wrong action even though the silence is real.'::text, 'false'::boolean, '30'::integer),
  ('EVIDENCE_INSUFFICIENT'::text, '{REJECT,DEFER}'::text[], 'Not enough evidence to act'::text, 'The engine reached this state on partial data - an unresolved WhatsApp handle, a stale silence detector, an unmeasured response time - and the reader will not act on it.'::text, 'true'::boolean, '80'::integer),
  ('LEAD_IS_DEAD'::text, '{REJECT}'::text[], 'Lead is genuinely dead'::text, 'The person has bought elsewhere or is no longer in the market. The lead should be closed, not recovered.'::text, 'false'::boolean, '50'::integer),
  ('NO_CAPACITY_NOW'::text, '{DEFER}'::text[], 'No capacity to act now'::text, 'The action is right and nobody is free to take it yet. Deferring records that as a capacity problem rather than losing it as a rejection.'::text, 'false'::boolean, '60'::integer),
  ('NOT_A_REAL_ENQUIRY'::text, '{REJECT}'::text[], 'Not a real car enquiry'::text, 'This lead is not a customer looking for a vehicle - a wrong number, a supplier, a bot, or a row the intake wiring created from something that was never an enquiry. The engine read the conversation correctly and the lead itself should never have existed.'::text, 'true'::boolean, '10'::integer),
  ('OTHER'::text, '{REJECT,DEFER}'::text[], 'Something else'::text, 'None of the above. The note is the whole record, so it has to say enough to be counted later.'::text, 'false'::boolean, '999'::integer),
  ('WAITING_ON_STOCK'::text, '{DEFER}'::text[], 'Waiting on a vehicle'::text, 'There is nothing worth saying to this customer until a suitable unit is on the lot.'::text, 'false'::boolean, '70'::integer),
  ('WRONG_OWNER'::text, '{REJECT,DEFER}'::text[], 'Wrong person is being asked to act'::text, 'The recommendation is right but it has been put in front of the wrong desk.'::text, 'false'::boolean, '40'::integer)
ON CONFLICT DO NOTHING;

-- lead_recovery_states
INSERT INTO public.lead_recovery_states (state, sort, meaning, engine_can_produce, blocked_by, requires) VALUES
  ('APPOINTMENT_PENDING'::text, '50'::integer, 'A booked appointment is outstanding.'::text, 'false'::boolean, 'NO_APPOINTMENT_TABLE'::text, 'An appointments table with a lead reference and a scheduled time. None exists in this schema - no table, no column, no event type - so no branch of lead_recovery_state() can return this and none has been written. Restoring it is an integration, not a code change.'::text),
  ('CLOSED_NO_OUTCOME'::text, '80'::integer, 'The lead is closed by status and no sale is recorded. Nothing is leaking because nothing is open.'::text, 'true'::boolean, NULL, 'nexus_lead_is_open(leads.status) false, and no purchase_history row.'::text),
  ('ENGAGED'::text, '40'::integer, 'Two-way conversation, dealership spoke last, inside the silence threshold.'::text, 'true'::boolean, NULL, 'A resolved outbound message newer than every inbound one, younger than silence_hours.'::text),
  ('ESCALATED'::text, '60'::integer, 'The lead was handed to a person and nothing has been said since.'::text, 'true'::boolean, NULL, 'leads.escalated_at set, and no resolved message after it.'::text),
  ('NEW_RISK'::text, '10'::integer, 'A lead exists and no conversation resolves to it. NEXUS knows nothing about what was said.'::text, 'true'::boolean, NULL, 'A leads row whose identity keys match no communication_logs row under the INV-002 rule.'::text),
  ('RECOVERED'::text, '70'::integer, 'A confirmed sale is recorded against this lead. Note: recovered LEAD, not revenue recovered BY NEXUS - v_lead_recovery.recovery_attribution_state answers that separately and answers it SALE_WITHOUT_RECOVERY_ACTION when no action was ever raised.'::text, 'true'::boolean, NULL, 'A purchase_history row carrying this lead_id. Nothing weaker counts.'::text),
  ('SILENT'::text, '30'::integer, 'The dealership sent the last message and the customer has not answered past the silence threshold.'::text, 'true'::boolean, NULL, 'A resolved outbound message newer than every inbound one, older than silence_hours.'::text),
  ('WAITING_RESPONSE'::text, '20'::integer, 'The customer sent the last message and the dealership has not replied.'::text, 'true'::boolean, NULL, 'A resolved inbound message newer than every resolved outbound message.'::text)
ON CONFLICT DO NOTHING;

-- policy_unmigrated_constant
INSERT INTO public.policy_unmigrated_constant (id, layer, location, snippet, current_value, kind, proposed_rule_type, proposed_rule_name, reaches_a_customer, seeded_as_rule, note, surveyed_on, created_at) VALUES
  ('0c4de0a2-76ab-4c78-b130-c677e1668a26'::uuid, 'N8N_WORKFLOW'::text, 'n8n-workflows/finance_calc_auto_loan_equity_credit_score.json — node "Calculate Equity &amp; Tier"'::text, 'const DISCLAIMER = ''... Min 20% down payment, max 60 months (UAE Central Bank rules).'''::text, '20% / 60 months, attributed to the UAE Central Bank'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'MAX_TENURE_MONTHS'::text, 'true'::boolean, 'true'::boolean, 'THE MOST URGENT ROW IN THIS TABLE. This is a regulatory claim, naming a regulator, sent to real customers on WhatsApp, resting on two constants nobody has checked against the instrument. Everything else here is a number; this is a sentence asserting the law. It should be the first thing verified or withdrawn.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('19b6370d-2d0b-497a-abca-918e703932a9'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/lib/unit-form.js:47'::text, 'VAT_RATE: 0.05,'::text, '0.05 (i.e. 5%)'::text, 'JURISDICTION'::text, 'TAX'::text, 'VAT_STANDARD_RATE'::text, 'false'::boolean, 'true'::boolean, 'The browser''s second copy of the VAT rate, and it is stored as a RATIO (0.05) while the database stores the same rule as a multiplication by 0.05 and the Policy Engine stores it as a PERCENT (5). Three renderings of one rule is exactly how a factor-of-100 error gets shipped. The file''s own comment already flags it as un-sourced and names the Policy Engine as where it belongs.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('21dd23e8-cee0-4169-9f49-58394db3de62'::uuid, 'DATABASE'::text, 'public.finance_quotes (constraint finance_quotes_credit_score_check)'::text, 'CHECK (credit_score &gt;= 300 AND credit_score &lt;= 900)'::text, '300 to 900'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'CREDIT_SCORE_SCALE_BOUNDS'::text, 'false'::boolean, 'false'::boolean, 'The bounds of the AECB scale, encoded as a constraint. Jurisdiction-specific: it is the UAE bureau''s scale, and a second country would need a second scale. Low urgency, listed for completeness.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('2a39e598-4022-44df-87c3-bcfb9d96fe69'::uuid, 'DATABASE'::text, 'public.v_needs_attention / public.v_team_performance'::text, 'response_time_minutes &gt; 5 ... ''breaches the 5-minute rule'''::text, '5 minutes'::text, 'OPERATIONAL'::text, 'MESSAGING'::text, 'LEAD_RESPONSE_SLA'::text, 'false'::boolean, 'false'::boolean, 'The same 5-minute threshold, written as a literal in two views rather than read from lead_recovery_settings. v_lead_recovery_coverage already asserts the two agree; that assertion is a string match on the view definition, so it detects drift but does not prevent it.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('40d2b417-9949-4efb-9e4e-6934d47ba8b3'::uuid, 'DATABASE'::text, 'public.finance_quotes (constraint finance_quotes_tenure_months_check)'::text, 'CHECK (tenure_months &gt;= 12 AND tenure_months &lt;= 60)'::text, '12 to 60 months'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'MAX_TENURE_MONTHS'::text, 'false'::boolean, 'true'::boolean, 'A jurisdiction rule enforced as a DDL constraint. This is the hardest kind to migrate and the easiest to forget: it is invisible to every grep of the application code, it silently rejects a legitimate 72-month quote if the rule ever changes, and altering it needs a migration and a table lock. The 60 matches screens/finance.js:308 and the customer-facing disclaimer, so three copies of one rule now exist in three layers.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('676ab26f-b806-4495-ba64-760e10cf6160'::uuid, 'N8N_WORKFLOW'::text, 'n8n-workflows/finance_calc_auto_loan_equity_credit_score.json — node "Calculate Equity &amp; Tier"'::text, 'const BANDS = [{min:746,aprLow:5.3,aprHigh:6.7,...},{711,...},{651,...},{541,8.2,9.65,...}]'::text, 'AECB cut-offs 746/711/651/541; APR 5.3%-9.65%; flat 2.50%-4.90%'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'INDICATIVE_APR_BANDS'::text, 'true'::boolean, 'false'::boolean, 'An indicative rate table read out to customers. Its own comment does the right thing — it names ADCB''s published bands and Emirates NBD''s 9.00% reducing / 9.65% APR ceiling as where the numbers came from, which is more provenance than anything else in this survey has. That provenance lives in a code comment where nothing can check it or date it. It is the single best candidate for a genuinely VERIFIED policy row, one per band, because a real source already exists — somebody just has to cite and date it. NOT seeded: the source is a lender''s published rate card, and transcribing it from a comment would launder a comment into a citation.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('74ff2f11-5bf7-4b87-94c5-6225a0ae0008'::uuid, 'N8N_WORKFLOW'::text, 'n8n-workflows/finance_calc_auto_loan_equity_credit_score.json — node "Calculate Equity &amp; Tier"'::text, '''Without salary transfer add roughly 1.4 percentage points.'' / ''~1.87x the flat rate over 60 months'''::text, '+1.4 pp; 1.87x'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'FLAT_TO_REDUCING_MULTIPLIER'::text, 'true'::boolean, 'false'::boolean, 'Two more customer-facing figures with no source. The 1.87 multiplier is arithmetic that depends on the 60-month tenure, so it silently becomes wrong if the tenure rule changes — a dependency no reader of either constant can see.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('764a2103-ea70-4bc4-bb54-fc9c92d4992f'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/screens/finance.js:292'::text, 'const MAX_LTV_PCT_CBUAE = 100 - MIN_DOWN_PAYMENT_PCT_CBUAE;'::text, '80%'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'MAX_LTV_PCT'::text, 'true'::boolean, 'true'::boolean, 'Derived arithmetically from the constant above rather than independently sourced, and printed as "the 80% CBUAE ceiling" at finance.js:1479 and in the bank-panel tooltip at finance.js:2456.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('79f4a229-b936-46c1-a1e3-1133350ec63d'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/screens/finance.js:303'::text, 'const ASSUMED_DOWN_PAYMENT_PCT_USED = 30;'::text, '30%'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'ASSUMED_DOWN_PAYMENT_PCT_USED'::text, 'true'::boolean, 'false'::boolean, 'A LENDER APPETITE assumption, not a law — the file is careful about the distinction and says the two are ten points of vehicle value apart. Deliberately NOT seeded: it is a claim about what UAE banks want, sourced to nothing, and seeding it would give a market assumption the same shelf as a regulation.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('8e021fec-4b53-42bb-ac18-d35d4d03a034'::uuid, 'DATABASE'::text, 'public.v_inventory_profit_sentinel'::text, 'COALESCE(s.promote_days,60), COALESCE(s.wholesale_days,180), COALESCE(s.min_reprice_margin_pct,8.00), COALESCE(s.enquiry_window_days,30), COALESCE(s.min_enquiry_sources,50), COALESCE(s.market_max_age_days,14)'::text, '60 / 180 / 8.00% / 30 / 50 / 14'::text, 'COMMERCIAL'::text, 'COMPLIANCE'::text, 'PROFIT_SENTINEL_THRESHOLDS'::text, 'false'::boolean, 'false'::boolean, 'Six commercial thresholds that decide whether a unit is recommended for PROMOTE, WHOLESALE or REPRICE. They are settings-table-backed (good) with hard-coded fallbacks (not good): min_reprice_margin_pct 8.00 in particular is a margin floor that shapes a manager-facing recommendation.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('940b317f-b908-4fb0-a023-b6e450f0c393'::uuid, 'DATABASE'::text, 'public.recompute_inventory_derived()'::text, 'round(b.price * 0.05) as vat_amount'::text, '5% of list price'::text, 'JURISDICTION'::text, 'TAX'::text, 'VAT_STANDARD_RATE'::text, 'true'::boolean, 'true'::boolean, 'The named example in the brief. A tax rate as a bare literal, with no source, no effective date and no owner. It writes inventory.vat_amount, which the Inventory drawer prints. Migrating it means calling policy_numeric(''AE'',''TAX'',''VAT_STANDARD_RATE'') — which today RAISES, correctly, because the seeded row is NOT_VERIFIED. Do not migrate until the row is verified, or the recompute starts failing.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('a3a1ed34-f00b-4754-bb9b-c0d39fe12c93'::uuid, 'DATABASE'::text, 'public.recompute_inventory_derived()'::text, 'round((b.gross_margin - ...) * 0.05) as recommended_commission  (two branches)'::text, '5% of net margin'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'SALES_COMMISSION_PCT_OF_NET_MARGIN'::text, 'false'::boolean, 'false'::boolean, 'A commission rate, not a tax, and it happens to share the number 5 with the VAT literal three lines above it — so a careless find-and-replace on 0.05 would corrupt one while fixing the other. Deliberately NOT seeded: it is one dealership''s commercial term and has no owner on record, so seeding it would be inventing a tenant policy nobody stated.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('a5795839-2fea-4fbb-b022-45f3005d9cfe'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/screens/finance.js:291'::text, 'const MIN_DOWN_PAYMENT_PCT_CBUAE = 20;'::text, '20%'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'MIN_DOWN_PAYMENT_PCT'::text, 'true'::boolean, 'true'::boolean, 'Named for a regulator nobody in this project has read. Printed into an explanatory sentence on the Finance Desk (finance.js:1107-1109) that attributes it to "the CBUAE 29/2011 legal floor".'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('b0d741df-afb4-4b1c-b578-87817a2f24df'::uuid, 'DATABASE'::text, 'public.v_deal_rescue / public.lead_recovery_propose()'::text, 'COALESCE(s.stalled_days,7) ... coalesce(s.reproposal_cooldown_days,7)'::text, '7 days'::text, 'OPERATIONAL'::text, 'COMPLIANCE'::text, 'ACTION_COOLDOWN_DAYS'::text, 'false'::boolean, 'false'::boolean, 'Cooldown and stall thresholds. Note inventory_action_policy.reproposal_cooldown_days DEFAULTs to 14 for the same idea — two defaults, two numbers, one concept.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('b1ac8952-5794-4335-b686-a0e2446e5d95'::uuid, 'DATABASE'::text, 'public.recompute_inventory_derived()'::text, 'coalesce(s.aging_warn_days, 90), coalesce(s.aging_critical_days, 120)'::text, '90 / 120 days'::text, 'COMMERCIAL'::text, 'COMPLIANCE'::text, 'INVENTORY_AGING_BANDS'::text, 'false'::boolean, 'false'::boolean, 'Fallbacks that fire when a dealership has no inventory_profit_settings row. A fallback IS an assertion: an unconfigured dealership silently gets 90/120 as if it had chosen them. Compare lib/unit-form.js, which falls back to 75 for the same band — the two disagree today.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('bcd91f21-7672-4f91-b65a-323f634aef6e'::uuid, 'N8N_WORKFLOW'::text, 'n8n-workflows/backup/dynamic_pricing.json — LLM system prompt'::text, '''Days in stock (holding cost = AED 50/day)'' and ''Gross margin preservation (minimum 8% margin)'''::text, 'AED 50/day; 8%'::text, 'COMMERCIAL'::text, 'COMPLIANCE'::text, 'HOLDING_COST_PER_DAY_AED'::text, 'false'::boolean, 'false'::boolean, 'THE AED 50/DAY IS STILL HERE. It was removed from lib/unit-form.js and from recompute_inventory_derived() on 2 Sep 2026 as the largest fabrication in the product — but it survives inside an LLM prompt, where no grep for a numeric constant and no database audit would find it, feeding a model that recommends price changes. A constant inside a prompt string is the worst hiding place for one. This is a backup/ copy in the repo; whether the published workflow on the box still carries it was NOT checked, because the box was not touched.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('bfaaceda-bea1-4146-a1e6-27a100acfe84'::uuid, 'DATABASE'::text, 'public.v_lead_recovery'::text, 'COALESCE(s.sla_first_response_minutes,5), COALESCE(s.silence_hours,12), COALESCE(s.stale_silence_hours,72), COALESCE(s.engagement_window_days,14)'::text, '5 min / 12 h / 72 h / 14 d'::text, 'OPERATIONAL'::text, 'MESSAGING'::text, 'LEAD_RESPONSE_SLA'::text, 'false'::boolean, 'false'::boolean, 'Internal SLA thresholds. Listed because the 5-minute figure is the one PRODUCT.md warns about being confused with the unsourced "10-second response doubles ad ROI" claim — they are unrelated, and the Policy Engine now holds the latter as UNKNOWN precisely so the two cannot be merged by accident.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('d0ead5ea-e582-43e5-91c9-353b96c00b1b'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/screens/finance.js:308'::text, 'const MAX_TENURE_MONTHS_CBUAE = 60;'::text, '60 months'::text, 'JURISDICTION'::text, 'FINANCE'::text, 'MAX_TENURE_MONTHS'::text, 'true'::boolean, 'true'::boolean, 'Third copy of the tenure rule, after the DDL constraint and the workflow disclaimer.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('d51fa984-e979-4c58-989e-e1358b020e36'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/screens/finance.js:255'::text, 'const MIN_VEHICLE_VALUE = 5000;'::text, 'AED 5,000'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'MIN_TRADE_IN_VALUE_AED'::text, 'false'::boolean, 'false'::boolean, 'Mirrors MIN_VEHICLE_VALUE_AED in the Finance Calc workflow. A currency threshold duplicated across the browser and the workflow, with no shared source — if one moves, quotes and validation disagree silently.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('dac0ec9b-1a54-4c62-9ea6-43bf9c29786e'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/lib/unit-form.js:49'::text, 'WARN_DAYS: 75,'::text, '75 days'::text, 'COMMERCIAL'::text, 'COMPLIANCE'::text, 'INVENTORY_AGING_BANDS'::text, 'false'::boolean, 'false'::boolean, 'DISAGREES WITH THE DATABASE, which uses 90 for the same band. The file says so in its own comment and leaves it deliberately: screens/competitors.js and screens/finance.js call deriveUnit() with no settings and have banded at 75 for weeks. This is a live one-figure-two-derivations violation waiting for the Policy Engine to resolve it.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone),
  ('ed8037a2-eba3-4ba9-824d-10102aa3ea93'::uuid, 'DASHBOARD'::text, 'apps/executive-dashboard/lib/unit-form.js:48'::text, 'COMMISSION_RATE: 0.05,'::text, '0.05 (i.e. 5%)'::text, 'COMMERCIAL'::text, 'FINANCE'::text, 'SALES_COMMISSION_PCT_OF_NET_MARGIN'::text, 'false'::boolean, 'false'::boolean, 'The browser''s copy of the commission rate, mirroring the database literal. Printed into a sentence at unit-form.js:545 and finance.js:3194.'::text, '2026-09-03'::date, '2026-09-03 04:06:21.841031+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- tenant_configuration_default
INSERT INTO public.tenant_configuration_default (setting_key, applies_to, value_kind, default_state, default_value, who_decides, provenance_required, rationale, engine_rule_when_absent, created_at) VALUES
  ('ai_tone'::text, 'tenant_configuration'::text, 'TEXT'::text, 'NO_DEFAULT'::text, NULL, 'DEALERSHIP'::text, 'true'::boolean, 'Tone reaches a customer verbatim and is the single cheapest way for software to embarrass a business. There is no neutral-by-accident default: an assistant that is chatty because nobody configured it is still chatty in this dealership name.'::text, 'Use the shipped neutral prompt. No persona, no nickname, no first-name familiarity, no exclamation marks, no emoji, no humour. State facts and offer a human.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('approval_rules'::text, 'tenant_configuration'::text, 'JSON'::text, 'PRODUCT_DEFAULT'::text, '{"default": {"requires_human": true}}'::jsonb, 'OPERATOR'::text, 'true'::boolean, 'This is the only setting whose default must be the RESTRICTIVE one. Every other default here answers "what do we show"; this one answers "may software act alone in a business name". The safe answer when nobody has decided is no.'::text, 'Require a named human approver for every action kind. An action kind absent from the rules object falls through to "default", which the shape CHECK makes mandatory - so an action nobody anticipated is still gated rather than silently automatic.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('brand_name'::text, 'tenant_configuration'::text, 'TEXT'::text, 'NO_DEFAULT'::text, NULL, 'DEALERSHIP'::text, 'false'::boolean, 'A trading name cannot be guessed, but it is also never truly unknown: public.tenants.name is on file for every dealership before anything else exists. So the honest fallback is inheritance, not invention, and the resolver reports it as INHERITED_FROM_TENANT rather than as the dealership having chosen it.'::text, 'Use public.tenants.name verbatim and label the state INHERITED_FROM_TENANT. Never construct a name from a slug, never abbreviate, never append a tagline.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('business_hours'::text, 'tenant_configuration'::text, 'JSON'::text, 'NO_DEFAULT'::text, NULL, 'DEALERSHIP'::text, 'true'::boolean, 'Assuming hours is the quiet way to invent an SLA breach. The same 40-minute wait is a failure at 11:00 and is not one at 03:00; a product that assumes 09:00-18:00 will accuse a rep of missing a promise nobody made, and a product that assumes 24/7 will promise a customer a reply nobody is there to send.'::text, 'Report elapsed wall-clock minutes and NEVER claim the showroom was open or closed. Do not schedule an outbound message against opening hours. Any first-response judgement rendered in this state must carry the words that the clock was not adjusted for opening hours.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('capabilities'::text, 'tenant_capability'::text, 'JSON'::text, 'NO_DEFAULT'::text, NULL, 'OPERATOR'::text, 'true'::boolean, 'Capabilities are rows in public.tenant_capability, not a blob on tenant_configuration, and there is deliberately no default: a default capability set is a fabricated integration. The absence of a row IS the answer, and it is the answer that fails toward absence.'::text, 'Treat every capability with no AVAILABLE row as NOT_AVAILABLE. Render the catalogue absent_means sentence. Never render zero, never render an empty chart, never infer the capability from the presence of a table.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('currency'::text, 'tenant_configuration'::text, 'TEXT'::text, 'PRODUCT_DEFAULT'::text, '"AED"'::jsonb, 'DEALERSHIP'::text, 'false'::boolean, 'AED is a PRODUCT_DEFAULT and very nearly a hard limit. Every monetary column in this schema is NAMED for the currency - amount_aed, price_aed, cost_aed, holding_cost_per_day_aed, recovered_value_aed - so a dealership on another currency is a schema change and an FX policy, not a settings change.'::text, 'Format money as AED. Changing this column today changes a LABEL and not a stored number, so a non-AED value here would MISLABEL every figure in the product. Treat a non-AED request as a blocked integration and say so.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('default_language'::text, 'tenant_configuration'::text, 'TEXT'::text, 'NO_DEFAULT'::text, NULL, 'DEALERSHIP'::text, 'false'::boolean, 'There is no honest product default for language. Defaulting to English is a guess about a customer, made once in a migration, that lands in a message a real person reads. In a market where a large share of enquiries arrive in Arabic, the cost of that guess is the enquiry.'::text, 'Reply in the language of the inbound message. Do not translate, do not assume English, and do not offer a language switch the dealership has not staffed. If no inbound text exists (a form submission with no free text), send nothing in this channel and route to a human.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('first_response_sla_minutes'::text, 'lead_recovery_settings'::text, 'INTEGER'::text, 'PRODUCT_DEFAULT'::text, '5'::jsonb, 'DEALERSHIP'::text, 'true'::boolean, 'The figure lives in lead_recovery_settings.sla_first_response_minutes and is NOT duplicated into tenant_configuration - a fifth copy of "5 minutes" in the table built to end copies would be self-defeating. What was missing was never a column; it was a DEFAULT WITH A STATE, so that a dealership which has not set it is distinguishable from one that chose 5. That distinction is what this row provides, and the resolver reports it as CONFIGURED versus PRODUCT_DEFAULT.'::text, 'Judge against 5 minutes and label the judgement, on every screen and in every message that quotes it, as this product default and not this dealership policy - which is what the Lead Recovery screen already says. Do not put the number in a customer-facing promise while it is in this state.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('followup_policy'::text, 'tenant_configuration'::text, 'JSON'::text, 'NO_DEFAULT'::text, NULL, 'DEALERSHIP'::text, 'true'::boolean, 'A follow-up cadence is unsolicited outbound messaging sent in the dealership name and, for WhatsApp, against their number and their template approvals. A default cadence is the product deciding to message somebody else customers.'::text, 'SEND NOTHING automatically. Surface the lead to a human queue instead. Absence of a policy is not a reason to fall back to a cadence; it is the reason there is no cadence.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone),
  ('timezone'::text, 'tenant_configuration'::text, 'TEXT'::text, 'PRODUCT_DEFAULT'::text, '"Asia/Dubai"'::jsonb, 'DEALERSHIP'::text, 'false'::boolean, 'Asia/Dubai is what the product ALREADY does: every n8n workflow carries timezone Asia/Dubai and apps/executive-dashboard/lib/format.js pins TZ to it with the comment that a manager in London saw 16:20 printed as 12:20. Recording it as a PRODUCT_DEFAULT does not make it more true - it makes the existing assumption visible and overridable instead of invisible and hard-coded.'::text, 'Render and schedule in Asia/Dubai and label every bare time with its zone. This is the product assumption, not this dealership statement: any screen that would otherwise imply the dealership chose this clock must say so.'::text, '2026-09-03 20:48:15.961058+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;

-- whatsapp_message_intent
INSERT INTO public.whatsapp_message_intent (code, label, description, is_business_initiated, template_category_if_required, created_at) VALUES
  ('FOLLOW_UP'::text, 'Follow-up'::text, 'The dealership re-opening a conversation that has gone quiet - silence detection, a promised call-back, a next-step nudge. Business-initiated.'::text, 'true'::boolean, 'UTILITY'::text, '2026-09-04 02:41:05.327268+00'::timestamp with time zone),
  ('MARKETING'::text, 'Marketing'::text, 'A promotional message: an offer, a new arrival, a price drop, a campaign. Business-initiated and, per the platform rules, gated on evidenced opt-in.'::text, 'true'::boolean, 'MARKETING'::text, '2026-09-04 02:41:05.327268+00'::timestamp with time zone),
  ('SERVICE_REPLY'::text, 'Service reply'::text, 'A reply to something the customer just asked. Only meaningful while the customer service window is open; outside it, it is a business-initiated message however it is labelled.'::text, 'false'::boolean, 'UTILITY'::text, '2026-09-04 02:41:05.327268+00'::timestamp with time zone),
  ('UTILITY'::text, 'Utility'::text, 'A transactional message about something the customer already has with the dealership: an appointment, an order, a document, a payment.'::text, 'true'::boolean, 'UTILITY'::text, '2026-09-04 02:41:05.327268+00'::timestamp with time zone)
ON CONFLICT DO NOTHING;
