/* Emits receiver.sdk.js by inlining the two node bodies verbatim.
 *
 * The point is that the repo cannot drift from the box. Both Code-node bodies
 * live in their own files, are syntax-checked by node, and are exercised by
 * receiver.test.js — and this script is the only thing that turns them into the
 * `jsCode` string n8n stores. Nothing is retyped, so nothing can be retyped
 * slightly differently.
 *
 *     node ops/n8n-google-lead-form/build-sdk.js
 */
const fs = require('fs');
const path = require('path');

const read = f => fs.readFileSync(path.join(__dirname, f), 'utf8');

/* The SDK parser allows a string literal and the + operator, and nothing else --
   no .join(), no template literals. So a node body becomes one literal per
   source line, concatenated. Readable in the repo, readable in the n8n editor,
   and byte-identical to the file it came from. */
const asLiteral = (src, indent) => src.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n')
  .map(line => indent + JSON.stringify(line + '\n'))
  .join(' +\n');
const SHAPE = read('extract-and-shape.node.js');
const VERIFY = read('verify-and-redact.node.js');

const SUPABASE = 'https://dsvuoovivysszdoiorch.supabase.co';

const sdk = `import { workflow, node, trigger, ifElse } from '@n8n/workflow-sdk';

/* GENERATED by ops/n8n-google-lead-form/build-sdk.js — do not hand-edit.
 * The two Code bodies come from extract-and-shape.node.js and
 * verify-and-redact.node.js, which are what receiver.test.js runs. */

const SUPABASE = ${JSON.stringify(SUPABASE)};

/* POST only. Google never sends a GET, and an endpoint that answers GET is a
 * free probe for whether a dealership's key exists. The Meta receivers need two
 * methods because Meta's subscription handshake is a GET; this one does not,
 * which also means there is only one webhook output and the connection trap
 * that silently swallowed every POST on the Cloud receiver cannot occur here. */
const hook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Google Lead Webhook',
    parameters: {
      httpMethod: 'POST',
      path: 'google-ads-lead/:key',
      authentication: 'none',
      responseMode: 'responseNode',
      options: { rawBody: true },
    },
  },
});

const shape = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Extract And Shape',
    parameters: { mode: 'runOnceForAllItems', language: 'javaScript',
      jsCode:
${asLiteral(SHAPE, '        ')} },
  },
});

const shaped = ifElse({
  version: 2.2,
  config: {
    name: 'Shaped Well Enough To Look Up?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.verdict }}',
          operator: { type: 'string', operation: 'equals' }, rightValue: 'SHAPED' }],
        combinator: 'and',
      },
    },
  },
});

/* An unresolvable key produces ZERO rows, which is the whole point of the
 * resolver returning a set. alwaysOutputData is on so the empty case still
 * reaches its own branch and can be answered deliberately, rather than the
 * workflow ending silently with Google holding no answer at all. */
const resolve = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Resolve Endpoint From URL Key',
    alwaysOutputData: true,
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_lead_endpoint_for_public_key',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_public_key: $json.public_key }) }}",
      options: { timeout: 10000 },
    },
  },
});

const resolved = ifElse({
  version: 2.2,
  config: {
    name: 'Endpoint Resolved?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.endpoint_id }}',
          operator: { type: 'string', operation: 'exists', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const verify = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Verify And Redact',
    parameters: { mode: 'runOnceForAllItems', language: 'javaScript',
      jsCode:
${asLiteral(VERIFY, '        ')} },
  },
});

const usable = ifElse({
  version: 2.2,
  config: {
    name: 'Authenticated?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.verdict }}',
          operator: { type: 'string', operation: 'startsWith' }, rightValue: 'ACCEPT' }],
        combinator: 'and',
      },
    },
  },
});

/* p_normalized is sent ONLY when it satisfies the Lead Event contract. Sending
 * a defective one makes nexus_record_lead_event raise, the workflow answer 5XX,
 * and Google retry a delivery that can never succeed — forever, for a form that
 * simply did not ask for a phone number. A defect is recorded instead. */
const record = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Record Lead Event',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_record_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_public_key: $json.public_key, p_external_event_id: $json.lead_id, p_origin_verified: 'shared_secret_in_body', p_payload_raw: $json.payload_raw, p_occurred_at: null, p_normalized: $json.normalized_defect === null ? $json.normalized : null }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* At-least-once is Google's documented contract, so a redelivery is ordinary.
 * It is answered 200 without touching the stored row: re-promoting is safe but
 * re-rejecting is not, and neither is worth the risk for a row we already hold. */
const isDuplicate = ifElse({
  version: 2.2,
  config: {
    name: 'Already Have This Lead?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.was_duplicate }}',
          operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const promotable = ifElse({
  version: 2.2,
  config: {
    name: 'A Real Customer We Can Reach?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: "={{ $('Verify And Redact').item.json.can_promote }}",
          operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const promote = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Promote To Lead',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_promote_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_event_id: $('Record Lead Event').item.json.event_id }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* Two things end here and they are NOT the same thing, so the phase says which:
 *   QUARANTINED — Google's own test button. The wire works and that is worth
 *                 recording; the fabricated customer must never reach the funnel.
 *   REJECTED    — a real delivery whose form did not collect enough to contact
 *                 anybody. That is a fact about the dealership's form, and it
 *                 should be visible as one rather than promoted and left to rot. */
const hold = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Hold Without Promoting',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_reject_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_event_id: $('Record Lead Event').item.json.event_id, p_phase: $('Verify And Redact').item.json.is_test ? 'QUARANTINED' : 'REJECTED', p_reason: $('Verify And Redact').item.json.is_test ? 'Google Ads test delivery (is_test=true). The delivery was authenticated and is recorded as evidence that the wire works; its fabricated customer is deliberately not promoted.' : ('The form did not collect enough to contact anyone: ' + $('Verify And Redact').item.json.normalized_defect + '. The delivery itself was fine - the lead form is what needs changing.') }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* Written out one by one rather than from a factory: the SDK parser rejects an
 * ArrowFunctionExpression, which cost a build once already. Both refusal nodes
 * take their status from the item, so the 4XX/5XX decision stays in the Code
 * node that has the reasons rather than being re-derived here. */
const refuseBeforeLookup = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond Refusal Before Lookup',
    parameters: {
      respondWith: 'text',
      responseBody: '={{ $json.respond_text }}',
      options: { responseCode: '={{ $json.respond_status }}' },
    },
  },
});

const refuseAfterLookup = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond Refusal After Lookup',
    parameters: {
      respondWith: 'text',
      responseBody: '={{ $json.respond_text }}',
      options: { responseCode: '={{ $json.respond_status }}' },
    },
  },
});

const okAlreadyKnown = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Already Known',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

const okLeadCreated = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Lead Created',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

const okNotPromoted = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Recorded Not Promoted',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

/* The unresolved-key answer is byte-identical to a wrong-key answer on purpose:
 * telling them apart would let anyone enumerate which endpoint keys exist. */
const respondUnresolved = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 403 Key Rejected',
    parameters: {
      respondWith: 'text',
      responseBody: 'GOOGLE_KEY_REJECTED',
      options: { responseCode: 403 },
    },
  },
});

export default workflow('google-ads-lead-form-receiver', 'Google Ads Lead Form - Inbound Receiver')
  .add(hook)
  .to(shape)
  .to(shaped
    .onFalse(refuseBeforeLookup)
    .onTrue(resolve.to(resolved
      .onFalse(respondUnresolved)
      .onTrue(verify.to(usable
        .onFalse(refuseAfterLookup)
        .onTrue(record.to(isDuplicate
          .onTrue(okAlreadyKnown)
          .onFalse(promotable
            .onTrue(promote.to(okLeadCreated))
            .onFalse(hold.to(okNotPromoted))))))))));
`;

fs.writeFileSync(path.join(__dirname, 'receiver.sdk.js'), sdk);

/* Round-trip, every time. The whole claim of this file is "the box runs what
   the repo holds", and an off-by-one in the line splitting broke that on the
   first attempt -- silently, because the code still looked right. So the
   generated literals are evaluated back and compared against the source files,
   and the build fails rather than emitting something that merely resembles
   them. */
let bad = 0;
for (const [i, name] of ['extract-and-shape.node.js', 'verify-and-redact.node.js'].entries()) {
  const block = [...sdk.matchAll(/jsCode:\n([\s\S]*?) \},\n/g)][i][1];
  // eslint-disable-next-line no-eval
  const roundTripped = eval('(' + block.trim() + ')');
  const source = read(name);
  if (roundTripped !== source) {
    bad++;
    console.error('MISMATCH ' + name + ': literal is ' + roundTripped.length +
                  ' bytes, file is ' + source.length);
  }
}
if (bad) { console.error('refusing to claim the repo matches the box'); process.exit(1); }
console.log('wrote receiver.sdk.js  (' + sdk.length + ' bytes); both bodies round-trip identical');
