import { workflow, node, trigger, ifElse } from '@n8n/workflow-sdk';

/* GENERATED by ops/n8n-google-lead-form/build-sdk.js — do not hand-edit.
 * The two Code bodies come from extract-and-shape.node.js and
 * verify-and-redact.node.js, which are what receiver.test.js runs. */

const SUPABASE = "https://dsvuoovivysszdoiorch.supabase.co";

/* POST only. Google never sends a GET, and an endpoint that answers GET is a
 * free probe for whether a dealership's key exists. The Meta receivers need two
 * methods because Meta's subscription handshake is a GET; this one does not,
 * which also means there is only one webhook output and the connection trap
 * that silently swallowed every POST on the Cloud receiver cannot occur here. */
const hook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Google Lead Webhook',
    parameters: {
      httpMethod: 'POST',
      path: 'google-ads-lead/:key',
      authentication: 'none',
      responseMode: 'responseNode',
      options: { rawBody: true },
    },
  },
});

const shape = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Extract And Shape',
    parameters: { mode: 'runOnceForAllItems', language: 'javaScript',
      jsCode:
        "/* The exact body of the \"Extract And Shape\" Code node in the n8n workflow\n" +
        " * \"Google Ads Lead Form - Inbound Receiver\".\n" +
        " *\n" +
        " * This runs BEFORE the dealership is known and BEFORE anything is\n" +
        " * authenticated. It therefore writes nothing, decides nothing about trust, and\n" +
        " * exists only to answer two questions cheaply: is this even shaped like a\n" +
        " * Google delivery, and which endpoint key is it addressed to.\n" +
        " *\n" +
        " * WHY THIS PROVIDER IS DIFFERENT FROM THE OTHER TWO, IN THE ONLY WAY THAT\n" +
        " * CHANGES THE DESIGN\n" +
        " *\n" +
        " * Meta signs its body. Google does not sign anything. Google authenticates by\n" +
        " * putting a plaintext shared secret -- `google_key` -- INSIDE the JSON, which\n" +
        " * means:\n" +
        " *\n" +
        " *   - there is no integrity over the body at all. `google_key` proves the\n" +
        " *     sender knew a secret; it proves nothing about the bytes around it. A\n" +
        " *     man in the middle who can read one delivery can forge every future one.\n" +
        " *     TLS is the only thing standing behind that, so this endpoint must never\n" +
        " *     be reachable over plain HTTP.\n" +
        " *   - the secret arrives in the same object as the customer, so redaction is\n" +
        " *     not tidiness here, it is the whole job. See `redact-and-normalize`.\n" +
        " *\n" +
        " * AND THE STATUS CODE IS PART OF THE CONTRACT, NOT AN AFTERTHOUGHT\n" +
        " *\n" +
        " * Google Ads documents lead delivery as at-least-once, retries a 5XX, and\n" +
        " * PERMANENTLY DISCARDS the lead on a 4XX. So the status is a decision about a\n" +
        " * real customer, and every refusal below states which it is choosing:\n" +
        " *\n" +
        " *   4XX -- \"this can never succeed, do not keep it\"   (a forgery, a wrong key,\n" +
        " *          a body with no lead id: identical bytes on retry, identical answer)\n" +
        " *   5XX -- \"this is ours to fix, hold it and come back\" (our secret is not\n" +
        " *          configured, our database is down, our bug)\n" +
        " *   200 -- accepted, duplicated, or stored-and-refused-for-a-stated-reason\n" +
        " *\n" +
        " * The one that looks wrong and is not: an UNCONFIGURED secret answers 5XX, not\n" +
        " * 4XX. While NEXUS is not configured, Google holds the lead and redelivers it.\n" +
        " * Answering 4XX there would throw away real customers to make our own\n" +
        " * misconfiguration quiet.\n" +
        " */\n" +
        "const item = $input.first();\n" +
        "const j = item.json || {};\n" +
        "const params = j.params || {};\n" +
        "const query = j.query || {};\n" +
        "\n" +
        "const refuse = (status, code, why, extra) => [{ json: Object.assign(\n" +
        "  { verdict: 'REFUSE', respond_status: status, respond_text: code,\n" +
        "    reason_code: code, why, wrote_nothing: true,\n" +
        "    google_will: status >= 500 ? 'RETRY' : 'DISCARD_PERMANENTLY' }, extra || {}) }];\n" +
        "\n" +
        "/* ---- which endpoint is this addressed to ----------------------------------\n" +
        "   The key is in the URL because Google's webhook URL is configured per lead\n" +
        "   form, in the dealership's OWN Google Ads account -- unlike Meta, where one\n" +
        "   callback URL serves every tenant. That makes the URL a legitimate place to\n" +
        "   carry the tenant identifier. It is an identifier and not an authenticator:\n" +
        "   anything bearing one is still unauthenticated until the secret matches. */\n" +
        "const publicKey = String(params.key || query.k || '').trim();\n" +
        "if (!publicKey) {\n" +
        "  return refuse(404, 'NO_ENDPOINT_KEY_IN_URL',\n" +
        "    'This URL carries no endpoint key. The webhook URL registered in Google Ads ' +\n" +
        "    'must be the full per-dealership URL, ending in /<endpoint public key>.');\n" +
        "}\n" +
        "/* Shape-checked here, before any database call, so that junk costs nothing and\n" +
        "   a probe cannot make us do work. Same alphabet as the column constraint\n" +
        "   lead_ingest_endpoint_public_key_shape. */\n" +
        "if (!/^[A-Za-z0-9_-]{24,128}$/.test(publicKey)) {\n" +
        "  return refuse(404, 'ENDPOINT_KEY_MALFORMED',\n" +
        "    'The key in the URL is not the shape an endpoint key has, so no lookup was ' +\n" +
        "    'attempted.');\n" +
        "}\n" +
        "\n" +
        "/* ---- the body ------------------------------------------------------------\n" +
        "   Read the raw bytes rather than n8n's parse, for the same reason as the Meta\n" +
        "   receivers: what arrived is evidence, and a re-encode is not what arrived. */\n" +
        "let raw = null, raw_source = null;\n" +
        "const bin = item.binary && (item.binary.data || item.binary.body);\n" +
        "if (bin && bin.data) { raw = Buffer.from(bin.data, 'base64'); raw_source = 'binary'; }\n" +
        "else if (typeof j.body === 'string') { raw = Buffer.from(j.body, 'utf8'); raw_source = 'string'; }\n" +
        "else if (j.body && typeof j.body === 'object') {\n" +
        "  raw = Buffer.from(JSON.stringify(j.body), 'utf8'); raw_source = 'reserialised';\n" +
        "}\n" +
        "if (!raw) {\n" +
        "  return refuse(500, 'RAW_BODY_NOT_AVAILABLE',\n" +
        "    'The webhook node handed this node no body at all. That is a fault in our ' +\n" +
        "    'own configuration, so Google is told to retry rather than to discard.');\n" +
        "}\n" +
        "\n" +
        "let payload;\n" +
        "try { payload = JSON.parse(raw.toString('utf8')); }\n" +
        "catch (e) {\n" +
        "  return refuse(400, 'BODY_NOT_JSON',\n" +
        "    'The body is not JSON. Retrying will send the same bytes, so there is ' +\n" +
        "    'nothing to hold.');\n" +
        "}\n" +
        "if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {\n" +
        "  return refuse(400, 'BODY_NOT_A_JSON_OBJECT', 'The body parsed but is not an object.');\n" +
        "}\n" +
        "\n" +
        "/* ---- the idempotency key -------------------------------------------------\n" +
        "   lead_id is the catalogue's dedup_field for this source and the ONLY thing\n" +
        "   that makes at-least-once delivery safe. Without it a redelivery is\n" +
        "   indistinguishable from a second customer, and the dealership is handed the\n" +
        "   same person twice. Nothing downstream can repair that, so it stops here. */\n" +
        "const leadId = String(payload.lead_id || '').trim();\n" +
        "if (!leadId) {\n" +
        "  return refuse(400, 'NO_LEAD_ID',\n" +
        "    'The delivery carries no lead_id, so redeliveries of it could not be told ' +\n" +
        "    'apart from new customers. A retry would carry the same defect.');\n" +
        "}\n" +
        "\n" +
        "/* Google's own test button sends is_test: true with fabricated details. It is\n" +
        "   allowed through the gate on purpose -- proving the wire works is exactly what\n" +
        "   it is for -- and is flagged here so that it is recorded and NEVER promoted\n" +
        "   into the dealership's funnel. A fake customer in a real pipeline is the\n" +
        "   defect this whole layer exists to avoid. */\n" +
        "const isTest = payload.is_test === true || String(payload.is_test || '').toLowerCase() === 'true';\n" +
        "\n" +
        "/* The secret is deliberately NOT returned in this node's output. It has to be\n" +
        "   read once, in the next node, to be compared -- and every value a Code node\n" +
        "   returns is written into n8n's own execution store. See the README: the\n" +
        "   webhook node's own output still holds it, and that is a real exposure this\n" +
        "   redaction does not close. */\n" +
        "return [{ json: {\n" +
        "  verdict: 'SHAPED',\n" +
        "  public_key: publicKey,\n" +
        "  lead_id: leadId,\n" +
        "  is_test: isTest,\n" +
        "  raw_source,\n" +
        "  /* Carried forward for the secret comparison in the next node and used\n" +
        "     nowhere else. */\n" +
        "  google_key_presented: typeof payload.google_key === 'string' ? payload.google_key : '',\n" +
        "  google_key_present: typeof payload.google_key === 'string' && payload.google_key !== '',\n" +
        "  /* The whole parsed body, for the redactor. It contains the secret. It must\n" +
        "     not reach a database column, a response body, or a log line. */\n" +
        "  parsed: payload,\n" +
        "} }];\n" },
  },
});

const shaped = ifElse({
  version: 2.2,
  config: {
    name: 'Shaped Well Enough To Look Up?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.verdict }}',
          operator: { type: 'string', operation: 'equals' }, rightValue: 'SHAPED' }],
        combinator: 'and',
      },
    },
  },
});

/* An unresolvable key produces ZERO rows, which is the whole point of the
 * resolver returning a set. alwaysOutputData is on so the empty case still
 * reaches its own branch and can be answered deliberately, rather than the
 * workflow ending silently with Google holding no answer at all. */
const resolve = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Resolve Endpoint From URL Key',
    alwaysOutputData: true,
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_lead_endpoint_for_public_key',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_public_key: $json.public_key }) }}",
      options: { timeout: 10000 },
    },
  },
});

const resolved = ifElse({
  version: 2.2,
  config: {
    name: 'Endpoint Resolved?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.endpoint_id }}',
          operator: { type: 'string', operation: 'exists', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const verify = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Verify And Redact',
    parameters: { mode: 'runOnceForAllItems', language: 'javaScript',
      jsCode:
        "/* The exact body of the \"Verify And Redact\" Code node in the n8n workflow\n" +
        " * \"Google Ads Lead Form - Inbound Receiver\".\n" +
        " *\n" +
        " * Two inputs, and the order matters: this node's own input is the resolved\n" +
        " * endpoint row, and the delivery comes from `Extract And Shape`. The endpoint\n" +
        " * is resolved FIRST because the secret is per-dealership -- see below -- and\n" +
        " * the secret is compared HERE, before anything is written.\n" +
        " *\n" +
        " * WHY THE DATABASE IS READ BEFORE THE REQUEST IS AUTHENTICATED\n" +
        " *\n" +
        " * That ordering is uncomfortable and it is deliberate. The alternative is one\n" +
        " * global `GOOGLE_LEAD_KEY` on the box, which authenticates before any lookup --\n" +
        " * and makes every dealership share one secret, so any dealer who knows their\n" +
        " * own key can post leads into any other dealer's pipeline. A shared secret\n" +
        " * across tenants is not a smaller problem than an indexed lookup; it is the\n" +
        " * exact tenancy defect this layer was built to remove. So: resolve, then\n" +
        " * authenticate, with the URL key shape-checked in the previous node so an\n" +
        " * unresolvable probe costs one index hit and nothing else.\n" +
        " *\n" +
        " * WHY THE REFUSAL IS THE SAME WHETHER THE KEY OR THE SECRET WAS WRONG\n" +
        " *\n" +
        " * Both answer 403 GOOGLE_KEY_REJECTED with the same body. Distinguishing them\n" +
        " * would let anyone enumerate which endpoint keys exist. The cost is real: a\n" +
        " * dealer who mistypes their key gets a silent refusal. That cost is paid at\n" +
        " * configuration time, where Google's \"send test data\" button shows the status\n" +
        " * -- and it is stated in the README rather than pretended away.\n" +
        " *\n" +
        " * WHAT REDACTION MEANS HERE, AND WHAT IT DOES NOT COVER\n" +
        " *\n" +
        " * `payload_raw` is built from a NAMED LIST, not filtered from Google's object.\n" +
        " * `google_key` is never on that list, so it cannot arrive by being forgotten,\n" +
        " * and neither can any field Google adds to this webhook next year. The one\n" +
        " * branch copied wholesale is `user_column_data` -- the customer's own answers,\n" +
        " * which are not ours to edit.\n" +
        " *\n" +
        " * This does NOT protect n8n's own execution store. The webhook node's output\n" +
        " * item holds the raw body, secret included, before this node runs. That is a\n" +
        " * real exposure and it is recorded in the README as unfixed.\n" +
        " */\n" +
        "\n" +
        "/* ---- the constraint, as measured against Postgres rather than assumed -----\n" +
        "   `lead_event_payload_carries_no_shared_secret` is a text match over the whole\n" +
        "   serialised JSON:\n" +
        "       payload_raw::text !~* '\"(google_key|app_secret|client_secret|\n" +
        "                                access_token|api_key|authorization)\"'\n" +
        "   It needs a real quote on both sides, so what actually trips it is a string --\n" +
        "   KEY OR VALUE, at any depth -- that is EXACTLY one of the six words. Measured\n" +
        "   on 7 September 2026:\n" +
        "\n" +
        "     {\"column_name\":\"google_key\"}                  REFUSED   (a question label)\n" +
        "     {\"column_id\":\"API_KEY\"}                       REFUSED   (the match is case-insensitive)\n" +
        "     {\"column_name\":\"my_api_key\"}                  accepted  (a substring never trips it)\n" +
        "     {\"string_value\":\"api_key\"}                    REFUSED   (an ANSWER, on its own)\n" +
        "     {\"string_value\":\"my api_key is broken\"}       accepted\n" +
        "     {\"string_value\":\"he said \\\"api_key\\\" loudly\"} accepted  (jsonb escapes the inner quotes)\n" +
        "     {\"string_value\":\"api_key \"}                   accepted  (one trailing space clears it)\n" +
        "     {\"a\":{\"b\":{\"c\":{\"d\":\"access_token\"}}}}        REFUSED   (depth is irrelevant)\n" +
        "\n" +
        "   The fourth line is the one that matters and it corrects something already\n" +
        "   shipped: the Meta receiver guarded question LABELS only, so a lead-form\n" +
        "   ANSWER of exactly \"authorization\" would have failed the insert and thrown\n" +
        "   away a real customer. And it guarded them with a SUBSTRING regex, which\n" +
        "   renamed harmless labels like \"my_api_key\" that never trip the constraint at\n" +
        "   all -- wrong in both directions from one wrong rule.\n" +
        "\n" +
        "   So the rule is exact-match, applied to VALUES (see the SECRET_KEYS note\n" +
        "   below for why keys need no repair), and the repair is the smallest thing that\n" +
        "   clears it: the string keeps the customer's word and gains a stated note.\n" +
        "   Nothing is deleted, nothing is silently rewritten, and `normalized` -- the\n" +
        "   column a salesperson actually reads -- is not covered by the constraint and is\n" +
        "   never touched at all. */\n" +
        "const BARE_CONSTRAINT_WORD =\n" +
        "  /^(google_key|app_secret|client_secret|access_token|api_key|authorization)$/i;\n" +
        "const CONSTRAINT_NOTE =\n" +
        "  ' (stored with this note because the bare word is refused by a database constraint; ' +\n" +
        "  'the customer wrote it exactly as it appears before this bracket)';\n" +
        "\n" +
        "/* Keys that carry an actual credential are DROPPED, which is a different job\n" +
        "   from constraint safety and is a longer list. Note that it CONTAINS all six\n" +
        "   constraint words, which is why the repair below runs on values only: a key\n" +
        "   equal to one of them never survives to be repaired, and a rename branch for\n" +
        "   keys would be unreachable code pretending to be a defence. Google carries the\n" +
        "   question label as a value -- user_column_data[].column_name -- so the value\n" +
        "   path is the one that fires. */\n" +
        "const SECRET_KEYS = new Set([\n" +
        "  'google_key', 'access_token', 'app_secret', 'client_secret', 'api_key', 'apikey',\n" +
        "  'authorization', 'refresh_token', 'secret', 'password', 'signature',\n" +
        "]);\n" +
        "\n" +
        "let strippedKeys = 0, annotatedValues = 0;\n" +
        "function safeCopy(v, depth) {\n" +
        "  if (depth > 12) return null;\n" +
        "  if (Array.isArray(v)) return v.map(x => safeCopy(x, depth + 1));\n" +
        "  if (v && typeof v === 'object') {\n" +
        "    const out = {};\n" +
        "    for (const [k, val] of Object.entries(v)) {\n" +
        "      const lower = String(k).toLowerCase();\n" +
        "      if (SECRET_KEYS.has(lower)) { strippedKeys++; continue; }\n" +
        "      out[k] = safeCopy(val, depth + 1);\n" +
        "    }\n" +
        "    return out;\n" +
        "  }\n" +
        "  if (typeof v === 'string' && BARE_CONSTRAINT_WORD.test(v)) {\n" +
        "    annotatedValues++;\n" +
        "    return v + CONSTRAINT_NOTE;\n" +
        "  }\n" +
        "  return v;\n" +
        "}\n" +
        "\n" +
        "/* -------------------------------------------------------------------------- */\n" +
        "const ep = $input.first().json || {};\n" +
        "const d = $('Extract And Shape').item.json;\n" +
        "\n" +
        "const refuse = (status, code, why, extra) => [{ json: Object.assign(\n" +
        "  { verdict: 'REFUSE', respond_status: status, respond_text: code,\n" +
        "    reason_code: code, why, wrote_nothing: true,\n" +
        "    google_will: status >= 500 ? 'RETRY' : 'DISCARD_PERMANENTLY' }, extra || {}) }];\n" +
        "\n" +
        "const secretRef = String(ep.secret_ref || '');\n" +
        "if (!secretRef) {\n" +
        "  return refuse(500, 'ENDPOINT_HAS_NO_SECRET_REF',\n" +
        "    'This endpoint resolved but names no secret, so no delivery to it can be ' +\n" +
        "    'authenticated. Ours to fix: Google is told to retry.');\n" +
        "}\n" +
        "/* $env is read by a name that came from our own database, never from the\n" +
        "   request. A caller cannot choose which environment variable is read. */\n" +
        "const expected = String($env[secretRef] || '');\n" +
        "if (!expected) {\n" +
        "  return refuse(500, 'ENDPOINT_SECRET_NOT_CONFIGURED',\n" +
        "    'The secret named ' + secretRef + ' is not set on this box, so nothing can ' +\n" +
        "    'be verified. Refusing every delivery until it is - and answering 5XX so ' +\n" +
        "    'Google holds the lead and redelivers it once it is set, rather than ' +\n" +
        "    'discarding a real customer to keep our misconfiguration quiet.',\n" +
        "    { secret_ref: secretRef });\n" +
        "}\n" +
        "\n" +
        "const sameString = (a, b) => {\n" +
        "  if (a.length !== b.length) return false;\n" +
        "  let diff = 0;\n" +
        "  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);\n" +
        "  return diff === 0;\n" +
        "};\n" +
        "if (!sameString(String(d.google_key_presented || ''), expected)) {\n" +
        "  /* One answer for \"no such endpoint\", \"wrong secret\" and \"no secret sent\", so\n" +
        "     that the endpoint key space cannot be enumerated from the outside. */\n" +
        "  return refuse(403, 'GOOGLE_KEY_REJECTED',\n" +
        "    'The google_key in the body did not match the secret registered for this ' +\n" +
        "    'endpoint. Nothing was written. Retrying sends the same key, so the lead ' +\n" +
        "    'is not held.');\n" +
        "}\n" +
        "\n" +
        "/* Everything below this line is authenticated. -------------------------------\n" +
        "   Also checked: that the endpoint we authenticated against is actually a\n" +
        "   Google one. A registered endpoint for another source reaching this URL means\n" +
        "   the wrong key was pasted into Google Ads, and a Meta or website endpoint\n" +
        "   would otherwise be handed a provenance it never declared -- which\n" +
        "   nexus_record_lead_event refuses in production anyway, as a 500. Better to say\n" +
        "   what happened. */\n" +
        "if (String(ep.source_key || '') !== 'google_ads_lead_form') {\n" +
        "  return refuse(400, 'ENDPOINT_IS_NOT_A_GOOGLE_ENDPOINT',\n" +
        "    'The key in this URL belongs to a \"' + ep.source_key + '\" endpoint. Register ' +\n" +
        "    'a google_ads_lead_form endpoint for this dealership and use its key here.');\n" +
        "}\n" +
        "\n" +
        "const p = d.parsed || {};\n" +
        "\n" +
        "/* ---- the customer, out of Google's column list ---------------------------- */\n" +
        "const byId = {}, byName = {};\n" +
        "for (const c of (Array.isArray(p.user_column_data) ? p.user_column_data : [])) {\n" +
        "  if (!c || typeof c !== 'object') continue;\n" +
        "  const val = String(c.string_value == null ? '' : c.string_value).trim();\n" +
        "  if (!val) continue;\n" +
        "  const id = String(c.column_id || '').trim().toUpperCase();\n" +
        "  const nm = String(c.column_name || '').trim().toLowerCase();\n" +
        "  if (id && byId[id] === undefined) byId[id] = val;\n" +
        "  if (nm && byName[nm] === undefined) byName[nm] = val;\n" +
        "}\n" +
        "/* column_id is Google's own enum and is stable; column_name is the advertiser's\n" +
        "   free text and is not. Prefer the enum, fall back to the label. */\n" +
        "const pick = (ids, names) => {\n" +
        "  for (const i of ids) if (byId[i]) return byId[i];\n" +
        "  for (const n of (names || [])) if (byName[n]) return byName[n];\n" +
        "  return '';\n" +
        "};\n" +
        "\n" +
        "let full_name = pick(['FULL_NAME'], ['full name', 'full_name', 'name']);\n" +
        "if (!full_name) {\n" +
        "  full_name = [pick(['FIRST_NAME'], ['first name']), pick(['LAST_NAME'], ['last name'])]\n" +
        "    .filter(Boolean).join(' ').trim();\n" +
        "}\n" +
        "const email = pick(['EMAIL', 'WORK_EMAIL'], ['email', 'e-mail']).toLowerCase();\n" +
        "\n" +
        "/* E.164 or nothing. Pasting a country code onto a number that was never local\n" +
        "   is how a dealership messages a stranger, so an unrecognised shape is reported\n" +
        "   as unparseable rather than repaired. */\n" +
        "function toE164(rawPhone) {\n" +
        "  const s = String(rawPhone || '').replace(/[^\\d+]/g, '');\n" +
        "  if (/^\\+[1-9]\\d{7,14}$/.test(s)) return s;\n" +
        "  const dg = s.replace(/\\D/g, '');\n" +
        "  if (/^00[1-9]\\d{7,14}$/.test(dg)) return '+' + dg.slice(2);\n" +
        "  if (/^971\\d{9}$/.test(dg)) return '+' + dg;\n" +
        "  if (/^0?5\\d{8}$/.test(dg)) return '+971' + dg.replace(/^0/, '');\n" +
        "  if (/^91[6-9]\\d{9}$/.test(dg)) return '+' + dg;\n" +
        "  return null;\n" +
        "}\n" +
        "const phoneRaw = pick(['PHONE_NUMBER', 'WORK_PHONE'], ['phone', 'phone number', 'mobile']);\n" +
        "const phone_e164 = toE164(phoneRaw);\n" +
        "\n" +
        "const vehicle = pick(['VEHICLE_MODEL', 'VEHICLE_TYPE'],\n" +
        "                     ['vehicle', 'model', 'car model', 'vehicle of interest']);\n" +
        "\n" +
        "/* Everything the form asked that is not one of the identity fields, kept as the\n" +
        "   customer's own words so a dealership sees the answers it paid to collect. */\n" +
        "const IDENTITY_IDS = new Set(['FULL_NAME', 'FIRST_NAME', 'LAST_NAME', 'EMAIL',\n" +
        "                              'WORK_EMAIL', 'PHONE_NUMBER', 'WORK_PHONE']);\n" +
        "const extras = [];\n" +
        "for (const c of (Array.isArray(p.user_column_data) ? p.user_column_data : [])) {\n" +
        "  if (!c || typeof c !== 'object') continue;\n" +
        "  const id = String(c.column_id || '').trim().toUpperCase();\n" +
        "  const val = String(c.string_value == null ? '' : c.string_value).trim();\n" +
        "  if (!val || IDENTITY_IDS.has(id)) continue;\n" +
        "  const label = String(c.column_name || c.column_id || 'answer').trim();\n" +
        "  extras.push(label + ': ' + val);\n" +
        "}\n" +
        "\n" +
        "const normalized = { full_name };\n" +
        "if (phone_e164) normalized.phone_e164 = phone_e164;\n" +
        "if (email) normalized.email = email;\n" +
        "if (vehicle) normalized.vehicle_of_interest = vehicle;\n" +
        "if (extras.length) normalized.message = extras.join(' | ');\n" +
        "\n" +
        "let defect = null;\n" +
        "if (!full_name) defect = 'NORMALIZED_FULL_NAME_REQUIRED';\n" +
        "else if (!phone_e164 && !email) defect = 'NORMALIZED_NEEDS_EMAIL_OR_PHONE';\n" +
        "\n" +
        "/* ---- payload_raw: an allowlist, and google_key is not on it ---------------- */\n" +
        "const payload_raw = {\n" +
        "  provider: 'google',\n" +
        "  lead_id: d.lead_id,\n" +
        "  api_version: p.api_version || null,\n" +
        "  form_id: p.form_id == null ? null : String(p.form_id),\n" +
        "  campaign_id: p.campaign_id == null ? null : String(p.campaign_id),\n" +
        "  adgroup_id: p.adgroup_id == null ? null : String(p.adgroup_id),\n" +
        "  creative_id: p.creative_id == null ? null : String(p.creative_id),\n" +
        "  asset_id: p.asset_id == null ? null : String(p.asset_id),\n" +
        "  /* Kept deliberately: offline conversion upload needs gclid later, and it is\n" +
        "     the only thing that will ever let this dealership prove to Google that the\n" +
        "     click became a sale. It is an ad click identifier, not a credential. */\n" +
        "  gcl_id: p.gcl_id == null ? null : String(p.gcl_id),\n" +
        "  is_test: d.is_test === true,\n" +
        "  ad_platform: 'google_search',\n" +
        "  ad_platform_confidence: 'ENDPOINT_REGISTERED',\n" +
        "  ad_platform_evidence:\n" +
        "    'Arrived on a registered google_ads_lead_form endpoint. Google does not say ' +\n" +
        "    'in the body which network served the ad, so this is the source, not the ' +\n" +
        "    'placement, and it is not guessed from the campaign name.',\n" +
        "  /* The one branch not allowlisted: the customer's own answers. */\n" +
        "  user_column_data: safeCopy(Array.isArray(p.user_column_data) ? p.user_column_data : [], 0),\n" +
        "  phone_unparseable: phone_e164 ? null : (phoneRaw || null),\n" +
        "  constraint_safety: {\n" +
        "    annotated_values: annotatedValues,\n" +
        "    stripped_secret_keys: strippedKeys,\n" +
        "  },\n" +
        "};\n" +
        "\n" +
        "return [{ json: {\n" +
        "  verdict: defect === null ? 'ACCEPT' : 'ACCEPT_UNPROMOTABLE',\n" +
        "  respond_status: 200,\n" +
        "  respond_text: 'ok',\n" +
        "  reason_code: defect === null ? 'GOOGLE_KEY_VERIFIED' : defect,\n" +
        "  tenant_id: ep.tenant_id,\n" +
        "  endpoint_id: ep.endpoint_id,\n" +
        "  public_key: d.public_key,\n" +
        "  lead_id: d.lead_id,\n" +
        "  is_test: d.is_test === true,\n" +
        "  origin_verified: 'shared_secret_in_body',\n" +
        "  payload_raw,\n" +
        "  /* Untouched on purpose: this is what a salesperson reads, and the constraint\n" +
        "     does not cover this column. */\n" +
        "  normalized,\n" +
        "  normalized_defect: defect,\n" +
        "  can_promote: defect === null && d.is_test !== true,\n" +
        "  annotated_values: annotatedValues,\n" +
        "  stripped_secret_keys: strippedKeys,\n" +
        "} }];\n" },
  },
});

const usable = ifElse({
  version: 2.2,
  config: {
    name: 'Authenticated?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.verdict }}',
          operator: { type: 'string', operation: 'startsWith' }, rightValue: 'ACCEPT' }],
        combinator: 'and',
      },
    },
  },
});

/* p_normalized is sent ONLY when it satisfies the Lead Event contract. Sending
 * a defective one makes nexus_record_lead_event raise, the workflow answer 5XX,
 * and Google retry a delivery that can never succeed — forever, for a form that
 * simply did not ask for a phone number. A defect is recorded instead. */
const record = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Record Lead Event',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_record_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_public_key: $json.public_key, p_external_event_id: $json.lead_id, p_origin_verified: 'shared_secret_in_body', p_payload_raw: $json.payload_raw, p_occurred_at: null, p_normalized: $json.normalized_defect === null ? $json.normalized : null }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* At-least-once is Google's documented contract, so a redelivery is ordinary.
 * It is answered 200 without touching the stored row: re-promoting is safe but
 * re-rejecting is not, and neither is worth the risk for a row we already hold. */
const isDuplicate = ifElse({
  version: 2.2,
  config: {
    name: 'Already Have This Lead?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: '={{ $json.was_duplicate }}',
          operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const promotable = ifElse({
  version: 2.2,
  config: {
    name: 'A Real Customer We Can Reach?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' },
        conditions: [{ leftValue: "={{ $('Verify And Redact').item.json.can_promote }}",
          operator: { type: 'boolean', operation: 'true', singleValue: true } }],
        combinator: 'and',
      },
    },
  },
});

const promote = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Promote To Lead',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_promote_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_event_id: $('Record Lead Event').item.json.event_id }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* Two things end here and they are NOT the same thing, so the phase says which:
 *   QUARANTINED — Google's own test button. The wire works and that is worth
 *                 recording; the fabricated customer must never reach the funnel.
 *   REJECTED    — a real delivery whose form did not collect enough to contact
 *                 anybody. That is a fact about the dealership's form, and it
 *                 should be visible as one rather than promoted and left to rot. */
const hold = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Hold Without Promoting',
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 1000,
    parameters: {
      method: 'POST',
      url: SUPABASE + '/rest/v1/rpc/nexus_reject_lead_event',
      authentication: 'predefinedCredentialType',
      nodeCredentialType: 'supabaseApi',
      sendHeaders: true,
      specifyHeaders: 'keypair',
      headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
      sendBody: true,
      contentType: 'json',
      specifyBody: 'json',
      jsonBody: "={{ JSON.stringify({ p_event_id: $('Record Lead Event').item.json.event_id, p_phase: $('Verify And Redact').item.json.is_test ? 'QUARANTINED' : 'REJECTED', p_reason: $('Verify And Redact').item.json.is_test ? 'Google Ads test delivery (is_test=true). The delivery was authenticated and is recorded as evidence that the wire works; its fabricated customer is deliberately not promoted.' : ('The form did not collect enough to contact anyone: ' + $('Verify And Redact').item.json.normalized_defect + '. The delivery itself was fine - the lead form is what needs changing.') }) }}",
      options: { timeout: 10000 },
    },
  },
});

/* Written out one by one rather than from a factory: the SDK parser rejects an
 * ArrowFunctionExpression, which cost a build once already. Both refusal nodes
 * take their status from the item, so the 4XX/5XX decision stays in the Code
 * node that has the reasons rather than being re-derived here. */
const refuseBeforeLookup = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond Refusal Before Lookup',
    parameters: {
      respondWith: 'text',
      responseBody: '={{ $json.respond_text }}',
      options: { responseCode: '={{ $json.respond_status }}' },
    },
  },
});

const refuseAfterLookup = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond Refusal After Lookup',
    parameters: {
      respondWith: 'text',
      responseBody: '={{ $json.respond_text }}',
      options: { responseCode: '={{ $json.respond_status }}' },
    },
  },
});

const okAlreadyKnown = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Already Known',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

const okLeadCreated = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Lead Created',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

const okNotPromoted = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 200 Recorded Not Promoted',
    parameters: { respondWith: 'text', responseBody: 'ok', options: { responseCode: 200 } },
  },
});

/* The unresolved-key answer is byte-identical to a wrong-key answer on purpose:
 * telling them apart would let anyone enumerate which endpoint keys exist. */
const respondUnresolved = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.5,
  config: {
    name: 'Respond 403 Key Rejected',
    parameters: {
      respondWith: 'text',
      responseBody: 'GOOGLE_KEY_REJECTED',
      options: { responseCode: 403 },
    },
  },
});

export default workflow('google-ads-lead-form-receiver', 'Google Ads Lead Form - Inbound Receiver')
  .add(hook)
  .to(shape)
  .to(shaped
    .onFalse(refuseBeforeLookup)
    .onTrue(resolve.to(resolved
      .onFalse(respondUnresolved)
      .onTrue(verify.to(usable
        .onFalse(refuseAfterLookup)
        .onTrue(record.to(isDuplicate
          .onTrue(okAlreadyKnown)
          .onFalse(promotable
            .onTrue(promote.to(okLeadCreated))
            .onFalse(hold.to(okNotPromoted))))))))));
